name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_androssy: ^0.0.9-alpha1
  flutter_andomie:
    path: ../

  faker: ^2.1.0
  get_it: ^7.3.0
  flutter_bloc: ^8.1.2
  cloud_firestore: ^4.7.0
  firebase_core: ^2.12.0
  firebase_core_platform_interface: ^4.8.0
  shared_preferences: ^2.1.1
  local_auth: ^2.1.6
  flutter_facebook_auth: ^5.0.11
  firebase_database: ^10.2.1
  firebase_auth: ^4.6.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
