name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_andomie:
    path: ../

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  translator: ^1.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/configs/
    - assets/contents/
    - assets/translations/

