name: flutter_andomie
description: Collection of utils with advanced style and controlling system.
version: 0.5.18
homepage: https://github.com/P-YMR/flutter_andomie.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter: