const kCountryNationalitiesInEnglish = {
  "IN": "Indian",
  "CN": "Chinese",
  "US": "American",
  "ID": "Indonesian",
  "PK": "Pakistani",
  "NG": "Nigerian",
  "BR": "Brazilian",
  "BD": "Bangladeshi",
  "RU": "Russian",
  "ET": "Ethiopian",
  "MX": "Mexican",
  "JP": "Japanese",
  "EG": "Egyptian",
  "PH": "Filipino",
  "CD": "Congolese",
  "VN": "Vietnamese",
  "IR": "Iranian",
  "TR": "Turkish",
  "DE": "German",
  "TH": "Thai",
  "GB": "British",
  "TZ": "Tanzanian",
  "FR": "French",
  "ZA": "South African",
  "IT": "Italian",
  "KE": "Kenyan",
  "MM": "Burmese",
  "CO": "Colombian",
  "KR": "South Korean",
  "SD": "Sudanese",
  "UG": "Ugandan",
  "ES": "Spanish",
  "DZ": "Algerian",
  "IQ": "Iraqi",
  "AR": "Argentine",
  "AF": "Afghan",
  "YE": "Yemeni",
  "CA": "Canadian",
  "PL": "Polish",
  "MA": "Moroccan",
  "AO": "Angolan",
  "UA": "Ukrainian",
  "UZ": "Uzbek",
  "MY": "Malaysian",
  "MZ": "Mozambican",
  "GH": "Ghanaian",
  "PE": "Peruvian",
  "SA": "Saudi",
  "MG": "Malagasy",
  "CI": "Ivorian",
  "NP": "Nepalese",
  "CM": "Cameroonian",
  "VE": "Venezuelan",
  "NE": "Nigerien",
  "AU": "Australian",
  "KP": "North Korean",
  "SY": "Syrian",
  "ML": "Malian",
  "BF": "Burkinabé",
  "LK": "Sri Lankan",
  "MW": "Malawian",
  "ZM": "Zambian",
  "KZ": "Kazakh",
  "TD": "Chadian",
  "CL": "Chilean",
  "RO": "Romanian",
  "SO": "Somali",
  "SN": "Senegalese",
  "GT": "Guatemalan",
  "NL": "Dutch",
  "EC": "Ecuadorian",
  "KH": "Cambodian",
  "ZW": "Zimbabwean",
  "GN": "Guinean",
  "BJ": "Beninese",
  "RW": "Rwandan",
  "BI": "Burundian",
  "BO": "Bolivian",
  "TN": "Tunisian",
  "SS": "South Sudanese",
  "HT": "Haitian",
  "BE": "Belgian",
  "JO": "Jordanian",
  "DO": "Dominican",
  "AE": "Emirati",
  "CU": "Cuban",
  "HN": "Honduran",
  "CZ": "Czech",
  "SE": "Swedish",
  "TJ": "Tajik",
  "PG": "Papua New Guinean",
  "PT": "Portuguese",
  "AZ": "Azerbaijani",
  "GR": "Greek",
  "HU": "Hungarian",
  "TG": "Togolese",
  "IL": "Israeli",
  "AT": "Austrian",
  "BY": "Belarusian",
  "CH": "Swiss",
  "SL": "Sierra Leonean",
  "LA": "Lao",
  "TM": "Turkmen",
  "LY": "Libyan",
  "KG": "Kyrgyz",
  "PY": "Paraguayan",
  "NI": "Nicaraguan",
  "BG": "Bulgarian",
  "RS": "Serbian",
  "SV": "Salvadoran",
  "CG": "Congolese",
  "DK": "Danish",
  "SG": "Singaporean",
  "LB": "Lebanese",
  "FI": "Finnish",
  "LR": "Liberian",
  "NO": "Norwegian",
  "SK": "Slovak",
  "PS": "Palestinian",
  "CF": "Central African",
  "OM": "Omani",
  "IE": "Irish",
  "NZ": "New Zealander",
  "MR": "Mauritanian",
  "CR": "Costa Rican",
  "KW": "Kuwaiti",
  "PA": "Panamanian",
  "HR": "Croatian",
  "GE": "Georgian",
  "ER": "Eritrean",
  "MN": "Mongolian",
  "UY": "Uruguayan",
  "BA": "Bosnian",
  "QA": "Qatari",
  "MD": "Moldovan",
  "NA": "Namibian",
  "AM": "Armenian",
  "LT": "Lithuanian",
  "JM": "Jamaican",
  "AL": "Albanian",
  "GM": "Gambian",
  "GA": "Gabonese",
  "BW": "Botswanan",
  "LS": "Basotho",
  "GW": "Bissau-Guinean",
  "SI": "Slovenian",
  "GQ": "Equatorial Guinean",
  "LV": "Latvian",
  "MK": "Macedonian",
  "BH": "Bahraini",
  "TT": "Trinidadian",
  "TL": "Timorese",
  "EE": "Estonian",
  "CY": "Cypriot",
  "MU": "Mauritian",
  "SZ": "Swazi",
  "DJ": "Djiboutian",
  "FJ": "Fijian",
  "KM": "Comorian",
  "GY": "Guyanese",
  "SB": "Solomon Islander",
  "BT": "Bhutanese",
  "LU": "Luxembourgish",
  "ME": "Montenegrin",
  "SR": "Surinamese",
  "MT": "Maltese",
  "MV": "Maldivian",
  "FM": "Micronesian",
  "CV": "Cape Verdean",
  "BN": "Bruneian",
  "BZ": "Belizean",
  "BS": "Bahamian",
  "IS": "Icelandic",
  "VU": "Ni-Vanuatu",
  "BB": "Barbadian",
  "ST": "São Toméan",
  "WS": "Samoan",
  "LC": "Saint Lucian",
  "KI": "I-Kiribati",
  "SC": "Seychellois",
  "GD": "Grenadian",
  "TO": "Tongan",
  "VC": "Vincentian",
  "AG": "Antiguan",
  "AD": "Andorran",
  "DM": "Dominican",
  "KN": "Kittitian",
  "LI": "Liechtensteiner",
  "MC": "Monégasque",
  "MH": "Marshallese",
  "SM": "San Marinese",
  "PW": "Palauan",
  "NR": "Nauruan",
  "TV": "Tuvaluan",
  "VA": "Vatican Citizen",
  "TW": "Taiwanese"
};
