const kCountryNamesInNative = {
  "IN": "भारत",
  "CN": "中国",
  "US": "United States",
  "ID": "Indonesia",
  "PK": "پاکستان",
  "NG": "Nigeria",
  "BR": "Brasil",
  "BD": "বাংলাদেশ",
  "RU": "Россия",
  "ET": "ኢትዮጵያ",
  "MX": "México",
  "JP": "日本",
  "EG": "مصر",
  "PH": "Pilipinas",
  "CD": "République Démocratique du Congo",
  "VN": "Việt Nam",
  "IR": "ایران",
  "TR": "Türkiye",
  "DE": "Deutschland",
  "TH": "ประเทศไทย",
  "GB": "United Kingdom",
  "TZ": "Tanzania",
  "FR": "France",
  "ZA": "South Africa",
  "IT": "Italia",
  "KE": "Kenya",
  "MM": "မြန်မာ",
  "CO": "Colombia",
  "KR": "대한민국",
  "SD": "السودان",
  "UG": "Uganda",
  "ES": "España",
  "DZ": "الجزائر",
  "IQ": "العراق",
  "AR": "Argentina",
  "AF": "افغانستان",
  "YE": "اليمن",
  "CA": "Canada",
  "PL": "Polska",
  "MA": "المغرب",
  "AO": "Angola",
  "UA": "Україна",
  "UZ": "Oʻzbekiston",
  "MY": "Malaysia",
  "MZ": "Moçambique",
  "GH": "Ghana",
  "PE": "Perú",
  "SA": "السعودية",
  "MG": "Madagasikara",
  "CI": "Côte d'Ivoire",
  "NP": "नेपाल",
  "CM": "Cameroun",
  "VE": "Venezuela",
  "NE": "Niger",
  "AU": "Australia",
  "KP": "조선",
  "SY": "سوريا",
  "ML": "Mali",
  "BF": "Burkina Faso",
  "LK": "ශ්‍රී ලංකාව",
  "MW": "Malawi",
  "ZM": "Zambia",
  "KZ": "Қазақстан",
  "TD": "Tchad",
  "CL": "Chile",
  "RO": "România",
  "SO": "Soomaaliya",
  "SN": "Sénégal",
  "GT": "Guatemala",
  "NL": "Nederland",
  "EC": "Ecuador",
  "KH": "កម្ពុជា",
  "ZW": "Zimbabwe",
  "GN": "Guinée",
  "BJ": "Bénin",
  "RW": "Rwanda",
  "BI": "Burundi",
  "BO": "Bolivia",
  "TN": "تونس",
  "SS": "South Sudan",
  "HT": "Ayiti",
  "BE": "België",
  "JO": "الأردن",
  "DO": "República Dominicana",
  "AE": "الإمارات العربية المتحدة",
  "CU": "Cuba",
  "HN": "Honduras",
  "CZ": "Česko",
  "SE": "Sverige",
  "TJ": "Тоҷикистон",
  "PG": "Papua New Guinea",
  "PT": "Portugal",
  "AZ": "Azərbaycan",
  "GR": "Ελλάδα",
  "HU": "Magyarország",
  "TG": "Togo",
  "IL": "ישראל",
  "AT": "Österreich",
  "BY": "Беларусь",
  "CH": "Schweiz",
  "SL": "Sierra Leone",
  "LA": "ປະເທດລາວ",
  "TM": "Türkmenistan",
  "LY": "ليبيا",
  "KG": "Кыргызстан",
  "PY": "Paraguay",
  "NI": "Nicaragua",
  "BG": "България",
  "RS": "Србија",
  "SV": "El Salvador",
  "CG": "République du Congo",
  "DK": "Danmark",
  "SG": "Singapore",
  "LB": "لبنان",
  "FI": "Suomi",
  "LR": "Liberia",
  "NO": "Norge",
  "SK": "Slovensko",
  "PS": "فلسطين",
  "CF": "République centrafricaine",
  "OM": "عُمان",
  "IE": "Éire",
  "NZ": "New Zealand",
  "MR": "موريتانيا",
  "CR": "Costa Rica",
  "KW": "الكويت",
  "PA": "Panamá",
  "HR": "Hrvatska",
  "GE": "საქართველო",
  "ER": "ኤርትራ",
  "MN": "Монгол Улс",
  "UY": "Uruguay",
  "BA": "Bosna i Hercegovina",
  "QA": "قطر",
  "MD": "Moldova",
  "NA": "Namibia",
  "AM": "Հայաստան",
  "LT": "Lietuva",
  "JM": "Jamaica",
  "AL": "Shqipëria",
  "GM": "The Gambia",
  "GA": "Gabon",
  "BW": "Botswana",
  "LS": "Lesotho",
  "GW": "Guiné-Bissau",
  "SI": "Slovenija",
  "GQ": "Guinea Ecuatorial",
  "LV": "Latvija",
  "MK": "Северна Македонија",
  "BH": "البحرين",
  "TT": "Trinidad and Tobago",
  "TL": "Timor-Leste",
  "EE": "Eesti",
  "CY": "Κύπρος",
  "MU": "Maurice",
  "SZ": "eSwatini",
  "DJ": "Djibouti",
  "FJ": "Fiji",
  "KM": "Comores",
  "GY": "Guyana",
  "SB": "Solomon Islands",
  "BT": "འབྲུག",
  "LU": "Lëtzebuerg",
  "ME": "Crna Gora",
  "SR": "Suriname",
  "MT": "Malta",
  "MV": "Maldives",
  "FM": "Federated States of Micronesia",
  "CV": "Cabo Verde",
  "BN": "Brunei",
  "BZ": "Belize",
  "BS": "Bahamas",
  "IS": "Ísland",
  "VU": "Vanuatu",
  "BB": "Barbados",
  "ST": "São Tomé e Príncipe",
  "WS": "Samoa",
  "LC": "Saint Lucia",
  "KI": "Kiribati",
  "SC": "Seychelles",
  "GD": "Grenada",
  "TO": "Tonga",
  "VC": "Saint Vincent and the Grenadines",
  "AG": "Antigua and Barbuda",
  "AD": "Andorra",
  "DM": "Dominica",
  "KN": "Saint Kitts and Nevis",
  "LI": "Liechtenstein",
  "MC": "Monaco",
  "MH": "Marshall Islands",
  "SM": "San Marino",
  "PW": "Palau",
  "NR": "Nauru",
  "TV": "Tuvalu",
  "VA": "Vatican City",
  "TW": "臺灣"
};
