import '../models/country.dart';

const kCountries = [
  Country(
    name: "India",
    nameNatively: "भारत",
    isoCode: "IN",
    iso3Code: "IND",
    phoneCode: "+91",
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    currencyNameNatively: "भारतीय रुपया",
    currencySymbol: "₹",
    languageCode: "hi",
    languageName: "Hindi",
    languageNameNatively: "हिन्दी",
    languages: [
      "hi",
      "en",
      "bn",
      "ta",
      "te",
      "mr",
      "gu",
      "ur",
      "pa",
      "kn",
      "ml",
      "or",
      "as",
      "ne",
      "si"
    ],
    digits: "0123456789",
    gdp: 6.5,
    population: 17.7,
    wealthiest: 3.3,
    flag: "🇮🇳",
  ),
  Country(
    name: "China",
    nameNatively: "中国",
    isoCode: "CN",
    iso3Code: "CHN",
    phoneCode: "+86",
    currencyCode: "CNY",
    currencyName: "Yuan Renminbi",
    currencyNameNatively: "人民币",
    currencySymbol: "¥",
    languageCode: "zh",
    languageName: "Chinese",
    languageNameNatively: "中文",
    languages: ["zh", "yue", "hak", "xiang", "gan", "min", "wu", "pinghua"],
    digits: "零一二三四五六七八九",
    gdp: 5.1,
    population: 18.0,
    wealthiest: 17.0,
    flag: "🇨🇳",
  ),
  Country(
    name: "United States of America",
    nameNatively: "United States",
    isoCode: "US",
    iso3Code: "USA",
    phoneCode: "+1",
    currencyCode: "USD",
    currencyName: "United States Dollar",
    currencyNameNatively: "Dollar",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "es", "zh", "fr", "de", "vi", "tag", "ar"],
    digits: "0123456789",
    gdp: 2.3,
    population: 4.2,
    wealthiest: 24.0,
    flag: "🇺🇸",
  ),
  Country(
    name: "Indonesia",
    nameNatively: "Indonesia",
    isoCode: "ID",
    iso3Code: "IDN",
    phoneCode: "+62",
    currencyCode: "IDR",
    currencyName: "Indonesian Rupiah",
    currencyNameNatively: "Rupiah Indonesia",
    currencySymbol: "Rp",
    languageCode: "id",
    languageName: "Indonesian",
    languageNameNatively: "Bahasa Indonesia",
    languages: ["id", "jv", "su", "min", "bal", "bug"],
    digits: "0123456789",
    gdp: 5.0,
    population: 3.5,
    wealthiest: 0.5,
    flag: "🇮🇩",
  ),
  Country(
    name: "Pakistan",
    nameNatively: "پاکستان",
    isoCode: "PK",
    iso3Code: "PAK",
    phoneCode: "+92",
    currencyCode: "PKR",
    currencyName: "Pakistani Rupee",
    currencyNameNatively: "پاکستانی روپیہ",
    currencySymbol: "₨",
    languageCode: "ur",
    languageName: "Urdu",
    languageNameNatively: "اردو",
    languages: ["ur", "en", "pa", "sd", "ps", "br"],
    digits: "0123456789",
    gdp: 3.5,
    population: 2.8,
    wealthiest: 0.3,
    flag: "🇵🇰",
  ),
  Country(
    name: "Nigeria",
    nameNatively: "Nigeria",
    isoCode: "NG",
    iso3Code: "NGA",
    phoneCode: "+234",
    currencyCode: "NGN",
    currencyName: "Nigerian Naira",
    currencyNameNatively: "Naira",
    currencySymbol: "₦",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "ha", "yo", "ig", "ff"],
    digits: "0123456789",
    gdp: 3.0,
    population: 2.6,
    wealthiest: 0.4,
    flag: "🇳🇬",
  ),
  Country(
    name: "Brazil",
    nameNatively: "Brasil",
    isoCode: "BR",
    iso3Code: "BRA",
    phoneCode: "+55",
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    currencyNameNatively: "Real Brasileiro",
    currencySymbol: "R\$",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt", "de", "it", "pl", "en"],
    digits: "0123456789",
    gdp: 1.1,
    population: 2.7,
    wealthiest: 2.1,
    flag: "🇧🇷",
  ),
  Country(
    name: "Bangladesh",
    nameNatively: "বাংলাদেশ",
    isoCode: "BD",
    iso3Code: "BGD",
    phoneCode: "+880",
    currencyCode: "BDT",
    currencyName: "Bangladeshi Taka",
    currencyNameNatively: "টাকা",
    currencySymbol: "৳",
    languageCode: "bn",
    languageName: "Bengali",
    languageNameNatively: "বাংলা",
    languages: ["bn", "en"],
    digits: "০১২৩৪৫৬৭৮৯",
    gdp: 6.4,
    population: 2.1,
    wealthiest: 0.4,
    flag: "🇧🇩",
  ),
  Country(
    name: "Russia",
    nameNatively: "Россия",
    isoCode: "RU",
    iso3Code: "RUS",
    phoneCode: "+7",
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    currencyNameNatively: "Рубль",
    currencySymbol: "₽",
    languageCode: "ru",
    languageName: "Russian",
    languageNameNatively: "Русский",
    languages: ["ru", "tt", "ba", "ch", "ce", "udm", "an", "os"],
    digits: "0123456789",
    gdp: -2.1,
    population: 1.9,
    wealthiest: 2.0,
    flag: "🇷🇺",
  ),
  Country(
    name: "Ethiopia",
    nameNatively: "ኢትዮጵያ",
    isoCode: "ET",
    iso3Code: "ETH",
    phoneCode: "+251",
    currencyCode: "ETB",
    currencyName: "Ethiopian Birr",
    currencyNameNatively: "Birr",
    currencySymbol: "Br",
    languageCode: "am",
    languageName: "Amharic",
    languageNameNatively: "አማርኛ",
    languages: ["et", "ru"],
    digits: "0123456789",
    gdp: 6.5,
    population: 0.5,
    wealthiest: 0.1,
    flag: "🇪🇹",
  ),
  Country(
    name: "Mexico",
    nameNatively: "México",
    isoCode: "MX",
    iso3Code: "MEX",
    phoneCode: "+52",
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    currencyNameNatively: "Peso Mexicano",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "na", "tlh", "hu"],
    digits: "0123456789",
    gdp: 3.1,
    population: 1.6,
    wealthiest: 1.5,
    flag: "🇲🇽",
  ),
  Country(
    name: "Japan",
    nameNatively: "日本",
    isoCode: "JP",
    iso3Code: "JPN",
    phoneCode: "+81",
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    currencyNameNatively: "円",
    currencySymbol: "¥",
    languageCode: "ja",
    languageName: "Japanese",
    languageNameNatively: "日本語",
    languages: ["ja"],
    digits: "０１２３４５６７８９",
    gdp: 1.0,
    population: 1.6,
    wealthiest: 4.9,
    flag: "🇯🇵",
  ),
  Country(
    name: "Egypt",
    nameNatively: "مصر",
    isoCode: "EG",
    iso3Code: "EGY",
    phoneCode: "+20",
    currencyCode: "EGP",
    currencyName: "Egyptian Pound",
    currencyNameNatively: "جنيه مصري",
    currencySymbol: "£",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "ber", "english"],
    digits: "0123456789",
    gdp: 5.6,
    population: 1.1,
    wealthiest: 0.4,
    flag: "🇪🇬",
  ),
  Country(
    name: "Philippines",
    nameNatively: "Pilipinas",
    isoCode: "PH",
    iso3Code: "PHL",
    phoneCode: "+63",
    currencyCode: "PHP",
    currencyName: "Philippine Peso",
    currencyNameNatively: "Piso",
    currencySymbol: "₱",
    languageCode: "tl",
    languageName: "Tagalog",
    languageNameNatively: "Filipino",
    languages: [
      "fil",
      "en",
      "ceb",
      "ilok",
      "hiligaynon",
      "bikol",
      "waray",
      "kapampangan"
    ],
    digits: "0123456789",
    gdp: 6.2,
    population: 1.4,
    wealthiest: 0.5,
    flag: "🇵🇭",
  ),
  Country(
    name: "Democratic Republic of the Congo",
    nameNatively: "République Démocratique du Congo",
    isoCode: "CD",
    iso3Code: "COD",
    phoneCode: "+243",
    currencyCode: "CDF",
    currencyName: "Congolese Franc",
    currencyNameNatively: "Franc Congolais",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "lkj", "sw", "kg"],
    digits: "0123456789",
    gdp: 5.5,
    population: 0.7,
    wealthiest: 0.2,
    flag: "🇨🇩",
  ),
  Country(
    name: "Vietnam",
    nameNatively: "Việt Nam",
    isoCode: "VN",
    iso3Code: "VNM",
    phoneCode: "+84",
    currencyCode: "VND",
    currencyName: "Vietnamese Dong",
    currencyNameNatively: "Đồng",
    currencySymbol: "₫",
    languageCode: "vi",
    languageName: "Vietnamese",
    languageNameNatively: "Tiếng Việt",
    languages: ["vi"],
    digits: "0123456789",
    gdp: 7.0,
    population: 1.3,
    wealthiest: 0.4,
    flag: "🇻🇳",
  ),
  Country(
    name: "Iran",
    nameNatively: "ایران",
    isoCode: "IR",
    iso3Code: "IRN",
    phoneCode: "+98",
    currencyCode: "IRR",
    currencyName: "Iranian Rial",
    currencyNameNatively: "ریال",
    currencySymbol: "﷼",
    languageCode: "fa",
    languageName: "Persian",
    languageNameNatively: "فارسی",
    languages: ["fa", "az", "kurd", "luri", "baluchi"],
    digits: "۰۱۲۳۴۵۶۷۸۹",
    gdp: 2.5,
    population: 1.1,
    wealthiest: 0.8,
    flag: "🇮🇷",
  ),
  Country(
    name: "Turkey",
    nameNatively: "Türkiye",
    isoCode: "TR",
    iso3Code: "TUR",
    phoneCode: "+90",
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    currencyNameNatively: "Türk Lirası",
    currencySymbol: "₺",
    languageCode: "tr",
    languageName: "Turkish",
    languageNameNatively: "Türkçe",
    languages: ["tr", "ku", "zazaki"],
    digits: "0123456789",
    gdp: 3.7,
    population: 1.1,
    wealthiest: 1.0,
    flag: "🇹🇷",
  ),
  Country(
    name: "Germany",
    nameNatively: "Deutschland",
    isoCode: "DE",
    iso3Code: "DEU",
    phoneCode: "+49",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "de",
    languageName: "German",
    languageNameNatively: "Deutsch",
    languages: ["de", "sq", "tr", "pl", "ru", "it", "cs"],
    digits: "0123456789",
    gdp: 1.8,
    population: 1.1,
    wealthiest: 5.0,
    flag: "🇩🇪",
  ),
  Country(
    name: "Thailand",
    nameNatively: "ประเทศไทย",
    isoCode: "TH",
    iso3Code: "THA",
    phoneCode: "+66",
    currencyCode: "THB",
    currencyName: "Thai Baht",
    currencyNameNatively: "บาท",
    currencySymbol: "฿",
    languageCode: "th",
    languageName: "Thai",
    languageNameNatively: "ไทย",
    languages: ["th", "en"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.9,
    wealthiest: 0.7,
    flag: "🇹🇭",
  ),
  Country(
    name: "United Kingdom",
    nameNatively: "United Kingdom",
    isoCode: "GB",
    iso3Code: "GBR",
    phoneCode: "+44",
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    currencyNameNatively: "Pound Sterling",
    currencySymbol: "£",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "cy", "gd", "kw"],
    digits: "0123456789",
    gdp: 3.9,
    population: 0.9,
    wealthiest: 3.3,
    flag: "🇬🇧",
  ),
  Country(
    name: "Tanzania",
    nameNatively: "Tanzania",
    isoCode: "TZ",
    iso3Code: "TZA",
    phoneCode: "+255",
    currencyCode: "TZS",
    currencyName: "Tanzanian Shilling",
    currencyNameNatively: "Shilling Tanzanian",
    currencySymbol: "TSh",
    languageCode: "sw",
    languageName: "Swahili",
    languageNameNatively: "Kiswahili",
    languages: ["sw", "en", "arabic"],
    digits: "0123456789",
    gdp: 6.7,
    population: 0.5,
    wealthiest: 0.1,
    flag: "🇹🇿",
  ),
  Country(
    name: "France",
    nameNatively: "France",
    isoCode: "FR",
    iso3Code: "FRA",
    phoneCode: "+33",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "de", "en", "pt"],
    digits: "0123456789",
    gdp: 1.7,
    population: 0.7,
    wealthiest: 3.3,
    flag: "🇫🇷",
  ),
  Country(
    name: "South Africa",
    nameNatively: "South Africa",
    isoCode: "ZA",
    iso3Code: "ZAF",
    phoneCode: "+27",
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    currencyNameNatively: "Rand",
    currencySymbol: "R",
    languageCode: "af",
    languageName: "Afrikaans",
    languageNameNatively: "Afrikaans",
    languages: ["af", "en", "zu", "xh", "af", "st", "ts", "tn", "ven"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.6,
    wealthiest: 0.5,
    flag: "🇿🇦",
  ),
  Country(
    name: "Italy",
    nameNatively: "Italia",
    isoCode: "IT",
    iso3Code: "ITA",
    phoneCode: "+39",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "it",
    languageName: "Italian",
    languageNameNatively: "Italiano",
    languages: ["it", "de", "sl", "fr"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.7,
    wealthiest: 2.2,
    flag: "🇮🇹",
  ),
  Country(
    name: "Kenya",
    nameNatively: "Kenya",
    isoCode: "KE",
    iso3Code: "KEN",
    phoneCode: "+254",
    currencyCode: "KES",
    currencyName: "Kenyan Shilling",
    currencyNameNatively: "Shilling Kenyalı",
    currencySymbol: "KSh",
    languageCode: "sw",
    languageName: "Swahili",
    languageNameNatively: "Kiswahili",
    languages: ["sw", "en", "arabic"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.4,
    wealthiest: 0.1,
    flag: "🇰🇪",
  ),
  Country(
    name: "Myanmar",
    nameNatively: "မြန်မာ",
    isoCode: "MM",
    iso3Code: "MMR",
    phoneCode: "+95",
    currencyCode: "MMK",
    currencyName: "Burmese Kyat",
    currencyNameNatively: "ကျပ်",
    currencySymbol: "K",
    languageCode: "my",
    languageName: "Burmese",
    languageNameNatively: "မြန်မာ",
    languages: ["my", "en"],
    digits: "၀၁၂၃၄၅၆၇၈၉",
    gdp: 6.0,
    population: 0.4,
    wealthiest: 0.1,
    flag: "🇲🇲",
  ),
  Country(
    name: "Colombia",
    nameNatively: "Colombia",
    isoCode: "CO",
    iso3Code: "COL",
    phoneCode: "+57",
    currencyCode: "COP",
    currencyName: "Colombian Peso",
    currencyNameNatively: "Peso Colombiano",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.5,
    wealthiest: 0.4,
    flag: "🇨🇴",
  ),
  Country(
    name: "South Korea",
    nameNatively: "대한민국",
    isoCode: "KR",
    iso3Code: "KOR",
    phoneCode: "+82",
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    currencyNameNatively: "원",
    currencySymbol: "₩",
    languageCode: "ko",
    languageName: "Korean",
    languageNameNatively: "한국어",
    languages: ["ko"],
    digits: "0123456789",
    gdp: 2.7,
    population: 0.7,
    wealthiest: 1.7,
    flag: "🇰🇷",
  ),
  Country(
    name: "Sudan",
    nameNatively: "السودان",
    isoCode: "SD",
    iso3Code: "SDN",
    phoneCode: "+249",
    currencyCode: "SDG",
    currencyName: "Sudanese Pound",
    currencyNameNatively: "جنيه سوداني",
    currencySymbol: "£",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 2.4,
    population: 0.3,
    wealthiest: 0.1,
    flag: "🇸🇩",
  ),
  Country(
    name: "Uganda",
    nameNatively: "Uganda",
    isoCode: "UG",
    iso3Code: "UGA",
    phoneCode: "+256",
    currencyCode: "UGX",
    currencyName: "Ugandan Shilling",
    currencyNameNatively: "Shilling Ugandan",
    currencySymbol: "USh",
    languageCode: "sw",
    languageName: "Swahili",
    languageNameNatively: "Kiswahili",
    languages: ["en", "sw", "ar", "ru", "lu"],
    digits: "0123456789",
    gdp: 5.1,
    population: 0.4,
    wealthiest: 0.1,
    flag: "🇺🇬",
  ),
  Country(
    name: "Spain",
    nameNatively: "España",
    isoCode: "ES",
    iso3Code: "ESP",
    phoneCode: "+34",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "ca", "gl", "eu"],
    digits: "0123456789",
    gdp: 4.3,
    population: 0.6,
    wealthiest: 1.9,
    flag: "🇪🇸",
  ),
  Country(
    name: "Algeria",
    nameNatively: "الجزائر",
    isoCode: "DZ",
    iso3Code: "DZA",
    phoneCode: "+213",
    currencyCode: "DZD",
    currencyName: "Algerian Dinar",
    currencyNameNatively: "دينار جزائري",
    currencySymbol: "د.ج",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "ber"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.3,
    wealthiest: 0.3,
    flag: "🇩🇿",
  ),
  Country(
    name: "Iraq",
    nameNatively: "العراق",
    isoCode: "IQ",
    iso3Code: "IRQ",
    phoneCode: "+964",
    currencyCode: "IQD",
    currencyName: "Iraqi Dinar",
    currencyNameNatively: "دينار عراقي",
    currencySymbol: "د.ع",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "kur", "tur"],
    digits: "0123456789",
    gdp: 5.4,
    population: 0.3,
    wealthiest: 0.2,
    flag: "🇮🇶",
  ),
  Country(
    name: "Argentina",
    nameNatively: "Argentina",
    isoCode: "AR",
    iso3Code: "ARG",
    phoneCode: "+54",
    currencyCode: "ARS",
    currencyName: "Argentine Peso",
    currencyNameNatively: "Peso Argentino",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.5,
    wealthiest: 1.0,
    flag: "🇦🇷",
  ),
  Country(
    name: "Afghanistan",
    nameNatively: "افغانستان",
    isoCode: "AF",
    iso3Code: "AFG",
    phoneCode: "+93",
    currencyCode: "AFN",
    currencyName: "Afghan Afghani",
    currencyNameNatively: "افغانی",
    currencySymbol: "؋",
    languageCode: "ps",
    languageName: "Pashto",
    languageNameNatively: "پښتو",
    languages: ["ps", "dr", "uz", "en"],
    digits: "۰۱۲۳۴۵۶۷۸۹",
    gdp: 2.3,
    population: 0.4,
    wealthiest: 0.1,
    flag: "🇦🇫",
  ),
  Country(
    name: "Yemen",
    nameNatively: "اليمن",
    isoCode: "YE",
    iso3Code: "YEM",
    phoneCode: "+967",
    currencyCode: "YER",
    currencyName: "Yemeni Rial",
    currencyNameNatively: "ريال يمني",
    currencySymbol: "﷼",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "so"],
    digits: "0123456789",
    gdp: -4.0,
    population: 0.3,
    wealthiest: 0.1,
    flag: "🇾🇪",
  ),
  Country(
    name: "Canada",
    nameNatively: "Canada",
    isoCode: "CA",
    iso3Code: "CAN",
    phoneCode: "+1",
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    currencyNameNatively: "Dollar canadien",
    currencySymbol: "\$",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["en", "fr"],
    digits: "0123456789",
    gdp: 3.7,
    population: 0.5,
    wealthiest: 2.0,
    flag: "🇨🇦",
  ),
  Country(
    name: "Poland",
    nameNatively: "Polska",
    isoCode: "PL",
    iso3Code: "POL",
    phoneCode: "+48",
    currencyCode: "PLN",
    currencyName: "Polish Zloty",
    currencyNameNatively: "Złoty",
    currencySymbol: "zł",
    languageCode: "pl",
    languageName: "Polish",
    languageNameNatively: "Polski",
    languages: ["pl"],
    digits: "0123456789",
    gdp: 4.7,
    population: 0.5,
    wealthiest: 0.7,
    flag: "🇵🇱",
  ),
  Country(
    name: "Morocco",
    nameNatively: "المغرب",
    isoCode: "MA",
    iso3Code: "MAR",
    phoneCode: "+212",
    currencyCode: "MAD",
    currencyName: "Moroccan Dirham",
    currencyNameNatively: "درهم مغربي",
    currencySymbol: "د.م.",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "ber"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.3,
    wealthiest: 0.5,
    flag: "🇲🇦",
  ),
  Country(
    name: "Angola",
    nameNatively: "Angola",
    isoCode: "AO",
    iso3Code: "AGO",
    phoneCode: "+244",
    currencyCode: "AOA",
    currencyName: "Angolan Kwanza",
    currencyNameNatively: "Kwanza Angolano",
    currencySymbol: "Kz",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 2.3,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇦🇴",
  ),
  Country(
    name: "Ukraine",
    nameNatively: "Україна",
    isoCode: "UA",
    iso3Code: "UKR",
    phoneCode: "+380",
    currencyCode: "UAH",
    currencyName: "Ukrainian Hryvnia",
    currencyNameNatively: "Гривня",
    currencySymbol: "₴",
    languageCode: "uk",
    languageName: "Ukrainian",
    languageNameNatively: "Українська",
    languages: ["uk"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.5,
    wealthiest: 0.6,
    flag: "🇺🇦",
  ),
  Country(
    name: "Uzbekistan",
    nameNatively: "Oʻzbekiston",
    isoCode: "UZ",
    iso3Code: "UZB",
    phoneCode: "+998",
    currencyCode: "UZS",
    currencyName: "Uzbekistani Som",
    currencyNameNatively: "Oʻzbek so‘mi",
    currencySymbol: "лв",
    languageCode: "uz",
    languageName: "Uzbek",
    languageNameNatively: "O'zbek",
    languages: ["uz", "ru"],
    digits: "0123456789",
    gdp: 5.5,
    population: 0.5,
    wealthiest: 0.3,
    flag: "🇺🇿",
  ),
  Country(
    name: "Malaysia",
    nameNatively: "Malaysia",
    isoCode: "MY",
    iso3Code: "MYS",
    phoneCode: "+60",
    currencyCode: "MYR",
    currencyName: "Malaysian Ringgit",
    currencyNameNatively: "Ringgit Malaysia",
    currencySymbol: "RM",
    languageCode: "ms",
    languageName: "Malay",
    languageNameNatively: "Bahasa Melayu",
    languages: ["ms", "en", "zh"],
    digits: "0123456789",
    gdp: 4.3,
    population: 0.4,
    wealthiest: 0.5,
    flag: "🇲🇾",
  ),
  Country(
    name: "Mozambique",
    nameNatively: "Moçambique",
    isoCode: "MZ",
    iso3Code: "MOZ",
    phoneCode: "+258",
    currencyCode: "MZN",
    currencyName: "Mozambican Metical",
    currencyNameNatively: "Metical Moçambicano",
    currencySymbol: "MT",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 3.8,
    population: 0.3,
    wealthiest: 0.2,
    flag: "🇲🇿",
  ),
  Country(
    name: "Ghana",
    nameNatively: "Ghana",
    isoCode: "GH",
    iso3Code: "GHA",
    phoneCode: "+233",
    currencyCode: "GHS",
    currencyName: "Ghanaian Cedi",
    currencyNameNatively: "Cedi",
    currencySymbol: "₵",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 5.5,
    population: 0.3,
    wealthiest: 0.2,
    flag: "🇬🇭",
  ),
  Country(
    name: "Peru",
    nameNatively: "Perú",
    isoCode: "PE",
    iso3Code: "PER",
    phoneCode: "+51",
    currencyCode: "PEN",
    currencyName: "Peruvian Nuevo Sol",
    currencyNameNatively: "Nuevo Sol",
    currencySymbol: "S/.",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "qu"],
    digits: "0123456789",
    gdp: 3.7,
    population: 0.3,
    wealthiest: 0.3,
    flag: "🇵🇪",
  ),
  Country(
    name: "Saudi Arabia",
    nameNatively: "السعودية",
    isoCode: "SA",
    iso3Code: "SAU",
    phoneCode: "+966",
    currencyCode: "SAR",
    currencyName: "Saudi Riyal",
    currencyNameNatively: "ريال سعودي",
    currencySymbol: "﷼",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: 2.1,
    population: 0.4,
    wealthiest: 1.3,
    flag: "🇸🇦",
  ),
  Country(
    name: "Madagascar",
    nameNatively: "Madagasikara",
    isoCode: "MG",
    iso3Code: "MDG",
    phoneCode: "+261",
    currencyCode: "MGA",
    currencyName: "Malagasy Ariary",
    currencyNameNatively: "Ariary",
    currencySymbol: "Ar",
    languageCode: "mg",
    languageName: "Malagasy",
    languageNameNatively: "Malagasy",
    languages: ["mg", "fr"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇲🇬",
  ),
  Country(
    name: "Ivory Coast",
    nameNatively: "Côte d'Ivoire",
    isoCode: "CI",
    iso3Code: "CIV",
    phoneCode: "+225",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "dioula", "bété"],
    digits: "0123456789",
    gdp: 6.0,
    population: 0.3,
    wealthiest: 0.3,
    flag: "🇨🇮",
  ),
  Country(
    name: "Nepal",
    nameNatively: "नेपाल",
    isoCode: "NP",
    iso3Code: "NPL",
    phoneCode: "+977",
    currencyCode: "NPR",
    currencyName: "Nepalese Rupee",
    currencyNameNatively: "रुपैया",
    currencySymbol: "₨",
    languageCode: "ne",
    languageName: "Nepali",
    languageNameNatively: "नेपाली",
    languages: ["ne", "en"],
    digits: "०१२३४५६७८९",
    gdp: 4.3,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇳🇵",
  ),
  Country(
    name: "Cameroon",
    nameNatively: "Cameroun",
    isoCode: "CM",
    iso3Code: "CMR",
    phoneCode: "+237",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "FCFA",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "en"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.3,
    wealthiest: 0.3,
    flag: "🇨🇲",
  ),
  Country(
    name: "Venezuela",
    nameNatively: "Venezuela",
    isoCode: "VE",
    iso3Code: "VEN",
    phoneCode: "+58",
    currencyCode: "VES",
    currencyName: "Venezuelan Bolívar",
    currencyNameNatively: "Bolívar venezolano",
    currencySymbol: "Bs",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: -10.0,
    population: 0.3,
    wealthiest: 0.2,
    flag: "🇻🇪",
  ),
  Country(
    name: "Niger",
    nameNatively: "Niger",
    isoCode: "NE",
    iso3Code: "NER",
    phoneCode: "+227",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "hausa"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇳🇪",
  ),
  Country(
    name: "Australia",
    nameNatively: "Australia",
    isoCode: "AU",
    iso3Code: "AUS",
    phoneCode: "+61",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    currencyNameNatively: "Dollar australien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.3,
    population: 0.3,
    wealthiest: 1.8,
    flag: "🇦🇺",
  ),
  Country(
    name: "North Korea",
    nameNatively: "조선",
    isoCode: "KP",
    iso3Code: "PRK",
    phoneCode: "+850",
    currencyCode: "KPW",
    currencyName: "North Korean Won",
    currencyNameNatively: "원",
    currencySymbol: "₩",
    languageCode: "ko",
    languageName: "Korean",
    languageNameNatively: "한국어",
    languages: ["ko"],
    digits: "0123456789",
    gdp: -0.5,
    population: 0.1,
    wealthiest: 0.0,
    flag: "🇰🇵",
  ),
  Country(
    name: "Syria",
    nameNatively: "سوريا",
    isoCode: "SY",
    iso3Code: "SYR",
    phoneCode: "+963",
    currencyCode: "SYP",
    currencyName: "Syrian Pound",
    currencyNameNatively: "ليرة سورية",
    currencySymbol: "£",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: -3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇾",
  ),
  Country(
    name: "Mali",
    nameNatively: "Mali",
    isoCode: "ML",
    iso3Code: "MLI",
    phoneCode: "+223",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "bambara"],
    digits: "0123456789",
    gdp: 5.4,
    population: 0.3,
    wealthiest: 0.1,
    flag: "🇲🇱",
  ),
  Country(
    name: "Burkina Faso",
    nameNatively: "Burkina Faso",
    isoCode: "BF",
    iso3Code: "BFA",
    phoneCode: "+226",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "mooré"],
    digits: "0123456789",
    gdp: 5.8,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇧🇫",
  ),
  Country(
    name: "Sri Lanka",
    nameNatively: "ශ්‍රී ලංකාව",
    isoCode: "LK",
    iso3Code: "LKA",
    phoneCode: "+94",
    currencyCode: "LKR",
    currencyName: "Sri Lankan Rupee",
    currencyNameNatively: "රුපියල්",
    currencySymbol: "Rs",
    languageCode: "si",
    languageName: "Sinhala",
    languageNameNatively: "සිංහල",
    languages: ["si", "ta", "en"],
    digits: "0123456789",
    gdp: 3.6,
    population: 0.2,
    wealthiest: 0.2,
    flag: "🇱🇰",
  ),
  Country(
    name: "Malawi",
    nameNatively: "Malawi",
    isoCode: "MW",
    iso3Code: "MWI",
    phoneCode: "+265",
    currencyCode: "MWK",
    currencyName: "Malawian Kwacha",
    currencyNameNatively: "Kwacha",
    currencySymbol: "MK",
    languageCode: "ny",
    languageName: "Chichewa",
    languageNameNatively: "Chichewa",
    languages: ["en", "ny"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇲🇼",
  ),
  Country(
    name: "Zambia",
    nameNatively: "Zambia",
    isoCode: "ZM",
    iso3Code: "ZMB",
    phoneCode: "+260",
    currencyCode: "ZMW",
    currencyName: "Zambian Kwacha",
    currencyNameNatively: "Kwacha",
    currencySymbol: "ZK",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "bemba"],
    digits: "0123456789",
    gdp: 4.2,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇿🇲",
  ),
  Country(
    name: "Kazakhstan",
    nameNatively: "Қазақстан",
    isoCode: "KZ",
    iso3Code: "KAZ",
    phoneCode: "+7",
    currencyCode: "KZT",
    currencyName: "Kazakhstani Tenge",
    currencyNameNatively: "Теңге",
    currencySymbol: "₸",
    languageCode: "kk",
    languageName: "Kazakh",
    languageNameNatively: "Қазақ тілі",
    languages: ["kk", "ru"],
    digits: "0123456789",
    gdp: 2.9,
    population: 0.2,
    wealthiest: 0.3,
    flag: "🇰🇿",
  ),
  Country(
    name: "Chad",
    nameNatively: "Tchad",
    isoCode: "TD",
    iso3Code: "TCD",
    phoneCode: "+235",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "CFA",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "ar"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇩",
  ),
  Country(
    name: "Chile",
    nameNatively: "Chile",
    isoCode: "CL",
    iso3Code: "CHL",
    phoneCode: "+56",
    currencyCode: "CLP",
    currencyName: "Chilean Peso",
    currencyNameNatively: "Peso Chileno",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 1.8,
    population: 0.3,
    wealthiest: 0.6,
    flag: "🇨🇱",
  ),
  Country(
    name: "Romania",
    nameNatively: "România",
    isoCode: "RO",
    iso3Code: "ROU",
    phoneCode: "+40",
    currencyCode: "RON",
    currencyName: "Romanian Leu",
    currencyNameNatively: "Leu",
    currencySymbol: "lei",
    languageCode: "ro",
    languageName: "Romanian",
    languageNameNatively: "Română",
    languages: ["ro"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.3,
    wealthiest: 0.4,
    flag: "🇷🇴",
  ),
  Country(
    name: "Somalia",
    nameNatively: "Soomaaliya",
    isoCode: "SO",
    iso3Code: "SOM",
    phoneCode: "+252",
    currencyCode: "SOS",
    currencyName: "Somali Shilling",
    currencyNameNatively: "Shilling Soomali",
    currencySymbol: "Sh",
    languageCode: "so",
    languageName: "Somali",
    languageNameNatively: "Soomaali",
    languages: ["so", "ar", "en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇸🇴",
  ),
  Country(
    name: "Senegal",
    nameNatively: "Sénégal",
    isoCode: "SN",
    iso3Code: "SEN",
    phoneCode: "+221",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇸🇳",
  ),
  Country(
    name: "Guatemala",
    nameNatively: "Guatemala",
    isoCode: "GT",
    iso3Code: "GTM",
    phoneCode: "+502",
    currencyCode: "GTQ",
    currencyName: "Guatemalan Quetzal",
    currencyNameNatively: "Quetzal Guatemalteco",
    currencySymbol: "Q",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 3.6,
    population: 0.2,
    wealthiest: 0.2,
    flag: "🇬🇹",
  ),
  Country(
    name: "Netherlands",
    nameNatively: "Nederland",
    isoCode: "NL",
    iso3Code: "NLD",
    phoneCode: "+31",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "nl",
    languageName: "Dutch",
    languageNameNatively: "Nederlands",
    languages: ["nl", "fr", "de"],
    digits: "0123456789",
    gdp: 2.2,
    population: 0.3,
    wealthiest: 1.0,
    flag: "🇳🇱",
  ),
  Country(
    name: "Ecuador",
    nameNatively: "Ecuador",
    isoCode: "EC",
    iso3Code: "ECU",
    phoneCode: "+593",
    currencyCode: "USD",
    currencyName: "United States Dollar",
    currencyNameNatively: "Dollar estadounidense",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "qu", "shuar"],
    digits: "0123456789",
    gdp: 3.4,
    population: 0.2,
    wealthiest: 0.3,
    flag: "🇪🇨",
  ),
  Country(
    name: "Cambodia",
    nameNatively: "កម្ពុជា",
    isoCode: "KH",
    iso3Code: "KHM",
    phoneCode: "+855",
    currencyCode: "KHR",
    currencyName: "Cambodian Riel",
    currencyNameNatively: "Riel Camboyano",
    currencySymbol: "៛",
    languageCode: "km",
    languageName: "Khmer",
    languageNameNatively: "ភាសាខ្មែរ",
    languages: ["km"],
    digits: "0123456789",
    gdp: 7.1,
    population: 0.2,
    wealthiest: 0.2,
    flag: "🇰🇭",
  ),
  Country(
    name: "Zimbabwe",
    nameNatively: "Zimbabwe",
    isoCode: "ZW",
    iso3Code: "ZWE",
    phoneCode: "+263",
    currencyCode: "ZWL",
    currencyName: "Zimbabwean Dollar",
    currencyNameNatively: "Dollar zimbabuense",
    currencySymbol: "Z\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "shona", "ndebele"],
    digits: "0123456789",
    gdp: 5.4,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇿🇼",
  ),
  Country(
    name: "Guinea",
    nameNatively: "Guinée",
    isoCode: "GN",
    iso3Code: "GIN",
    phoneCode: "+224",
    currencyCode: "GNF",
    currencyName: "Guinean Franc",
    currencyNameNatively: "Franco guineano",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr", "fula", "maninka", "susu"],
    digits: "0123456789",
    gdp: 6.0,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇬🇳",
  ),
  Country(
    name: "Benin",
    nameNatively: "Bénin",
    isoCode: "BJ",
    iso3Code: "BEN",
    phoneCode: "+229",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 6.2,
    population: 0.2,
    wealthiest: 0.1,
    flag: "🇧🇯",
  ),
  Country(
    name: "Rwanda",
    nameNatively: "Rwanda",
    isoCode: "RW",
    iso3Code: "RWA",
    phoneCode: "+250",
    currencyCode: "RWF",
    currencyName: "Rwandan Franc",
    currencyNameNatively: "Franco ruandese",
    currencySymbol: "Fr",
    languageCode: "rw",
    languageName: "Kinyarwanda",
    languageNameNatively: "Kinyarwanda",
    languages: ["rw", "en", "fr"],
    digits: "0123456789",
    gdp: 8.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇷🇼",
  ),
  Country(
    name: "Burundi",
    nameNatively: "Burundi",
    isoCode: "BI",
    iso3Code: "BDI",
    phoneCode: "+257",
    currencyCode: "BIF",
    currencyName: "Burundian Franc",
    currencyNameNatively: "Franco burundés",
    currencySymbol: "Fr",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["rw", "fr"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇮",
  ),
  Country(
    name: "Bolivia",
    nameNatively: "Bolivia",
    isoCode: "BO",
    iso3Code: "BOL",
    phoneCode: "+591",
    currencyCode: "BOB",
    currencyName: "Bolivian Boliviano",
    currencyNameNatively: "Boliviano",
    currencySymbol: "Bs.",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "aym", "quech"],
    digits: "0123456789",
    gdp: 2.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇴",
  ),
  Country(
    name: "Tunisia",
    nameNatively: "تونس",
    isoCode: "TN",
    iso3Code: "TUN",
    phoneCode: "+216",
    currencyCode: "TND",
    currencyName: "Tunisian Dinar",
    currencyNameNatively: "Dinar tunecino",
    currencySymbol: "د.ت",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "fr"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇹🇳",
  ),
  Country(
    name: "South Sudan",
    nameNatively: "South Sudan",
    isoCode: "SS",
    iso3Code: "SSD",
    phoneCode: "+211",
    currencyCode: "SSP",
    currencyName: "South Sudanese Pound",
    currencyNameNatively: "South Sudanese Pound",
    currencySymbol: "SSP",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["ar", "en", "zande"],
    digits: "0123456789",
    gdp: -1.5,
    population: 0.1,
    wealthiest: 0.0,
    flag: "🇸🇸",
  ),
  Country(
    name: "Haiti",
    nameNatively: "Ayiti",
    isoCode: "HT",
    iso3Code: "HTI",
    phoneCode: "+509",
    currencyCode: "HTG",
    currencyName: "Haitian Gourde",
    currencyNameNatively: "Gourde haïtien",
    currencySymbol: "G",
    languageCode: "ht",
    languageName: "Haitian Creole",
    languageNameNatively: "Kreyòl ayisyen",
    languages: ["ht", "fr"],
    digits: "0123456789",
    gdp: -1.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇭🇹",
  ),
  Country(
    name: "Belgium",
    nameNatively: "België",
    isoCode: "BE",
    iso3Code: "BEL",
    phoneCode: "+32",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "nl",
    languageName: "Dutch",
    languageNameNatively: "Nederlands",
    languages: ["nl", "fr", "de"],
    digits: "0123456789",
    gdp: 2.1,
    population: 0.1,
    wealthiest: 0.7,
    flag: "🇧🇪",
  ),
  Country(
    name: "Jordan",
    nameNatively: "الأردن",
    isoCode: "JO",
    iso3Code: "JOR",
    phoneCode: "+962",
    currencyCode: "JOD",
    currencyName: "Jordanian Dinar",
    currencyNameNatively: "دينار أردني",
    currencySymbol: "JD",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇯🇴",
  ),
  Country(
    name: "Dominican Republic",
    nameNatively: "República Dominicana",
    isoCode: "DO",
    iso3Code: "DOM",
    phoneCode: "+1",
    currencyCode: "DOP",
    currencyName: "Dominican Peso",
    currencyNameNatively: "Peso Dominicano",
    currencySymbol: "RD\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 5.3,
    population: 0.2,
    wealthiest: 0.3,
    flag: "🇩🇴",
  ),
  Country(
    name: "United Arab Emirates",
    nameNatively: "الإمارات العربية المتحدة",
    isoCode: "AE",
    iso3Code: "ARE",
    phoneCode: "+971",
    currencyCode: "AED",
    currencyName: "United Arab Emirates Dirham",
    currencyNameNatively: "درهم إماراتي",
    currencySymbol: "د.إ",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: 2.9,
    population: 0.1,
    wealthiest: 0.9,
    flag: "🇦🇪",
  ),
  Country(
    name: "Cuba",
    nameNatively: "Cuba",
    isoCode: "CU",
    iso3Code: "CUB",
    phoneCode: "+53",
    currencyCode: "CUP",
    currencyName: "Cuban Peso",
    currencyNameNatively: "Peso cubano",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: -1.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇨🇺",
  ),
  Country(
    name: "Honduras",
    nameNatively: "Honduras",
    isoCode: "HN",
    iso3Code: "HND",
    phoneCode: "+504",
    currencyCode: "HNL",
    currencyName: "Honduran Lempira",
    currencyNameNatively: "Lempira",
    currencySymbol: "L",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 3.7,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇭🇳",
  ),
  Country(
    name: "Czech Republic",
    nameNatively: "Česko",
    isoCode: "CZ",
    iso3Code: "CZE",
    phoneCode: "+420",
    currencyCode: "CZK",
    currencyName: "Czech Koruna",
    currencyNameNatively: "Koruna",
    currencySymbol: "Kč",
    languageCode: "cs",
    languageName: "Czech",
    languageNameNatively: "Čeština",
    languages: ["cs", "sk"],
    digits: "0123456789",
    gdp: 2.9,
    population: 0.1,
    wealthiest: 0.4,
    flag: "🇨🇿",
  ),
  Country(
    name: "Sweden",
    nameNatively: "Sverige",
    isoCode: "SE",
    iso3Code: "SWE",
    phoneCode: "+46",
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    currencyNameNatively: "Krona",
    currencySymbol: "kr",
    languageCode: "sv",
    languageName: "Swedish",
    languageNameNatively: "Svenska",
    languages: ["sv"],
    digits: "0123456789",
    gdp: 3.1,
    population: 0.1,
    wealthiest: 0.6,
    flag: "🇸🇪",
  ),
  Country(
    name: "Tajikistan",
    nameNatively: "Тоҷикистон",
    isoCode: "TJ",
    iso3Code: "TJK",
    phoneCode: "+992",
    currencyCode: "TJS",
    currencyName: "Tajikistani Somoni",
    currencyNameNatively: "Somoni",
    currencySymbol: "ЅМ",
    languageCode: "tg",
    languageName: "Tajik",
    languageNameNatively: "Тоҷикӣ",
    languages: ["tg", "ru"],
    digits: "0123456789",
    gdp: 7.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇯",
  ),
  Country(
    name: "Papua New Guinea",
    nameNatively: "Papua New Guinea",
    isoCode: "PG",
    iso3Code: "PNG",
    phoneCode: "+675",
    currencyCode: "PGK",
    currencyName: "Papua New Guinean Kina",
    currencyNameNatively: "Kina",
    currencySymbol: "K",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "tok pisin", "hiri motu"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇵🇬",
  ),
  Country(
    name: "Portugal",
    nameNatively: "Portugal",
    isoCode: "PT",
    iso3Code: "PRT",
    phoneCode: "+351",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.1,
    wealthiest: 0.4,
    flag: "🇵🇹",
  ),
  Country(
    name: "Azerbaijan",
    nameNatively: "Azərbaycan",
    isoCode: "AZ",
    iso3Code: "AZE",
    phoneCode: "+994",
    currencyCode: "AZN",
    currencyName: "Azerbaijani Manat",
    currencyNameNatively: "Manat Azərbaycan",
    currencySymbol: "₼",
    languageCode: "az",
    languageName: "Azerbaijani",
    languageNameNatively: "Azərbaycan dili",
    languages: ["az", "ru"],
    digits: "0123456789",
    gdp: 3.6,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇦🇿",
  ),
  Country(
    name: "Greece",
    nameNatively: "Ελλάδα",
    isoCode: "GR",
    iso3Code: "GRC",
    phoneCode: "+30",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Ευρώ",
    currencySymbol: "€",
    languageCode: "el",
    languageName: "Greek",
    languageNameNatively: "Ελληνικά",
    languages: ["el"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.5,
    flag: "🇬🇷",
  ),
  Country(
    name: "Hungary",
    nameNatively: "Magyarország",
    isoCode: "HU",
    iso3Code: "HUN",
    phoneCode: "+36",
    currencyCode: "HUF",
    currencyName: "Hungarian Forint",
    currencyNameNatively: "Forint",
    currencySymbol: "Ft",
    languageCode: "hu",
    languageName: "Hungarian",
    languageNameNatively: "Magyar",
    languages: ["hu"],
    digits: "0123456789",
    gdp: 4.2,
    population: 0.1,
    wealthiest: 0.4,
    flag: "🇭🇺",
  ),
  Country(
    name: "Togo",
    nameNatively: "Togo",
    isoCode: "TG",
    iso3Code: "TGO",
    phoneCode: "+228",
    currencyCode: "XOF",
    currencyName: "West African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "CFA",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇬",
  ),
  Country(
    name: "Israel",
    nameNatively: "ישראל",
    isoCode: "IL",
    iso3Code: "ISR",
    phoneCode: "+972",
    currencyCode: "ILS",
    currencyName: "Israeli New Shekel",
    currencyNameNatively: "שקל חדש",
    currencySymbol: "₪",
    languageCode: "he",
    languageName: "Hebrew",
    languageNameNatively: "עברית",
    languages: ["he", "ar"],
    digits: "0123456789",
    gdp: 3.3,
    population: 0.1,
    wealthiest: 0.6,
    flag: "🇮🇱",
  ),
  Country(
    name: "Austria",
    nameNatively: "Österreich",
    isoCode: "AT",
    iso3Code: "AUT",
    phoneCode: "+43",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "de",
    languageName: "German",
    languageNameNatively: "Deutsch",
    languages: ["de"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.1,
    wealthiest: 0.5,
    flag: "🇦🇹",
  ),
  Country(
    name: "Belarus",
    nameNatively: "Беларусь",
    isoCode: "BY",
    iso3Code: "BLR",
    phoneCode: "+375",
    currencyCode: "BYN",
    currencyName: "Belarusian Ruble",
    currencyNameNatively: "Рубель",
    currencySymbol: "Br",
    languageCode: "be",
    languageName: "Belarusian",
    languageNameNatively: "Беларуская",
    languages: ["be", "ru"],
    digits: "0123456789",
    gdp: -0.9,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇾",
  ),
  Country(
    name: "Switzerland",
    nameNatively: "Schweiz",
    isoCode: "CH",
    iso3Code: "CHE",
    phoneCode: "+41",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    currencyNameNatively: "Franken",
    currencySymbol: "CHF",
    languageCode: "de",
    languageName: "German",
    languageNameNatively: "Deutsch",
    languages: ["de", "fr", "it", "rm"],
    digits: "0123456789",
    gdp: 2.1,
    population: 0.1,
    wealthiest: 0.9,
    flag: "🇨🇭",
  ),
  Country(
    name: "Sierra Leone",
    nameNatively: "Sierra Leone",
    isoCode: "SL",
    iso3Code: "SLE",
    phoneCode: "+232",
    currencyCode: "SLL",
    currencyName: "Sierra Leonean Leone",
    currencyNameNatively: "Leone",
    currencySymbol: "₨",
    languageCode: "si",
    languageName: "Slovenian",
    languageNameNatively: "Slovenščina",
    languages: ["si"],
    digits: "0123456789",
    gdp: 3.4,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇱",
  ),
  Country(
    name: "Laos",
    nameNatively: "ປະເທດລາວ",
    isoCode: "LA",
    iso3Code: "LAO",
    phoneCode: "+856",
    currencyCode: "LAK",
    currencyName: "Lao Kip",
    currencyNameNatively: "Kip",
    currencySymbol: "₭",
    languageCode: "lo",
    languageName: "Lao",
    languageNameNatively: "ພາສາລາວ",
    languages: ["lo"],
    digits: "0123456789",
    gdp: 4.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇦",
  ),
  Country(
    name: "Turkmenistan",
    nameNatively: "Türkmenistan",
    isoCode: "TM",
    iso3Code: "TKM",
    phoneCode: "+993",
    currencyCode: "TMT",
    currencyName: "Turkmenistan Manat",
    currencyNameNatively: "Manat Türkmenistan",
    currencySymbol: "m",
    languageCode: "tk",
    languageName: "Turkmen",
    languageNameNatively: "Türkmen dili",
    languages: ["tk"],
    digits: "0123456789",
    gdp: 6.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇲",
  ),
  Country(
    name: "Libya",
    nameNatively: "ليبيا",
    isoCode: "LY",
    iso3Code: "LBY",
    phoneCode: "+218",
    currencyCode: "LYD",
    currencyName: "Libyan Dinar",
    currencyNameNatively: "دينار ليبي",
    currencySymbol: "د.ل",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: -3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇾",
  ),
  Country(
    name: "Kyrgyzstan",
    nameNatively: "Кыргызстан",
    isoCode: "KG",
    iso3Code: "KGZ",
    phoneCode: "+996",
    currencyCode: "KGS",
    currencyName: "Kyrgyzstani Som",
    currencyNameNatively: "Сом",
    currencySymbol: "с",
    languageCode: "ky",
    languageName: "Kyrgyz",
    languageNameNatively: "Қырғыз тили",
    languages: ["ky", "ru"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇰🇬",
  ),
  Country(
    name: "Paraguay",
    nameNatively: "Paraguay",
    isoCode: "PY",
    iso3Code: "PRY",
    phoneCode: "+595",
    currencyCode: "PYG",
    currencyName: "Paraguayan Guarani",
    currencyNameNatively: "Guaraní paraguayo",
    currencySymbol: "₲",
    languageCode: "gn",
    languageName: "Guarani",
    languageNameNatively: "Guaraní",
    languages: ["gn"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇵🇾",
  ),
  Country(
    name: "Nicaragua",
    nameNatively: "Nicaragua",
    isoCode: "NI",
    iso3Code: "NIC",
    phoneCode: "+505",
    currencyCode: "NIO",
    currencyName: "Nicaraguan Córdoba",
    currencyNameNatively: "Córdoba",
    currencySymbol: "C\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 4.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇳🇮",
  ),
  Country(
    name: "Bulgaria",
    nameNatively: "България",
    isoCode: "BG",
    iso3Code: "BGR",
    phoneCode: "+359",
    currencyCode: "BGN",
    currencyName: "Bulgarian Lev",
    currencyNameNatively: "Лев",
    currencySymbol: "лв",
    languageCode: "bg",
    languageName: "Bulgarian",
    languageNameNatively: "Български",
    languages: ["bg"],
    digits: "0123456789",
    gdp: 3.8,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇧🇬",
  ),
  Country(
    name: "Serbia",
    nameNatively: "Србија",
    isoCode: "RS",
    iso3Code: "SRB",
    phoneCode: "+381",
    currencyCode: "RSD",
    currencyName: "Serbian Dinar",
    currencyNameNatively: "Динар",
    currencySymbol: "дин.",
    languageCode: "sr",
    languageName: "Serbian",
    languageNameNatively: "Српски",
    languages: ["sr"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.3,
    flag: "🇷🇸",
  ),
  Country(
    name: "El Salvador",
    nameNatively: "El Salvador",
    isoCode: "SV",
    iso3Code: "SLV",
    phoneCode: "+503",
    currencyCode: "USD",
    currencyName: "El Salvadoran Colón",
    currencyNameNatively: "Colón",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 2.4,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇻",
  ),
  Country(
    name: "Republic of the Congo",
    nameNatively: "République du Congo",
    isoCode: "CG",
    iso3Code: "COG",
    phoneCode: "+242",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "CFA",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇨🇬",
  ),
  Country(
    name: "Denmark",
    nameNatively: "Danmark",
    isoCode: "DK",
    iso3Code: "DNK",
    phoneCode: "+45",
    currencyCode: "DKK",
    currencyName: "Danish Krone",
    currencyNameNatively: "Krone",
    currencySymbol: "kr",
    languageCode: "da",
    languageName: "Danish",
    languageNameNatively: "Dansk",
    languages: ["da"],
    digits: "0123456789",
    gdp: 2.2,
    population: 0.1,
    wealthiest: 0.5,
    flag: "🇩🇰",
  ),
  Country(
    name: "Singapore",
    nameNatively: "Singapore",
    isoCode: "SG",
    iso3Code: "SGP",
    phoneCode: "+65",
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    currencyNameNatively: "Dollar Singapura",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "zh", "ms", "ta"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.8,
    flag: "🇸🇬",
  ),
  Country(
    name: "Lebanon",
    nameNatively: "لبنان",
    isoCode: "LB",
    iso3Code: "LBN",
    phoneCode: "+961",
    currencyCode: "LBP",
    currencyName: "Lebanese Pound",
    currencyNameNatively: "جنيه لبناني",
    currencySymbol: "ل.ل",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "fr", "en"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇱🇧",
  ),
  Country(
    name: "Finland",
    nameNatively: "Suomi",
    isoCode: "FI",
    iso3Code: "FIN",
    phoneCode: "+358",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "fi",
    languageName: "Finnish",
    languageNameNatively: "Suomi",
    languages: ["fi", "sv"],
    digits: "0123456789",
    gdp: 2.1,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇫🇮",
  ),
  Country(
    name: "Liberia",
    nameNatively: "Liberia",
    isoCode: "LR",
    iso3Code: "LBR",
    phoneCode: "+231",
    currencyCode: "LRD",
    currencyName: "Liberian Dollar",
    currencyNameNatively: "Dollar liberiano",
    currencySymbol: "L\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇷",
  ),
  Country(
    name: "Norway",
    nameNatively: "Norge",
    isoCode: "NO",
    iso3Code: "NOR",
    phoneCode: "+47",
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    currencyNameNatively: "Krone",
    currencySymbol: "kr",
    languageCode: "no",
    languageName: "Norwegian",
    languageNameNatively: "Norsk",
    languages: ["no"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.5,
    flag: "🇳🇴",
  ),
  Country(
    name: "Slovakia",
    nameNatively: "Slovensko",
    isoCode: "SK",
    iso3Code: "SVK",
    phoneCode: "+421",
    currencyCode: "EUR",
    currencyName: "Slovak Koruna",
    currencyNameNatively: "Koruna slovenská",
    currencySymbol: "€",
    languageCode: "sk",
    languageName: "Slovak",
    languageNameNatively: "Slovenčina",
    languages: ["sk"],
    digits: "0123456789",
    gdp: 3.3,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇸🇰",
  ),
  Country(
    name: "Palestine",
    nameNatively: "فلسطين",
    isoCode: "PS",
    iso3Code: "PSE",
    phoneCode: "+970",
    currencyCode: "ILS",
    currencyName: "Israeli New Shekel",
    currencyNameNatively: "שקל חדש",
    currencySymbol: "₪",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇵🇸",
  ),
  Country(
    name: "Central African Republic",
    nameNatively: "République centrafricaine",
    isoCode: "CF",
    iso3Code: "CAF",
    phoneCode: "+236",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "CFA",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇨🇫",
  ),
  Country(
    name: "Oman",
    nameNatively: "عُمان",
    isoCode: "OM",
    iso3Code: "OMN",
    phoneCode: "+968",
    currencyCode: "OMR",
    currencyName: "Omani Rial",
    currencyNameNatively: "ريال عماني",
    currencySymbol: "ر.ع.",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇴🇲",
  ),
  Country(
    name: "Ireland",
    nameNatively: "Éire",
    isoCode: "IE",
    iso3Code: "IRL",
    phoneCode: "+353",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "ga"],
    digits: "0123456789",
    gdp: 5.1,
    population: 0.1,
    wealthiest: 0.6,
    flag: "🇮🇪",
  ),
  Country(
    name: "New Zealand",
    nameNatively: "New Zealand",
    isoCode: "NZ",
    iso3Code: "NZL",
    phoneCode: "+64",
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    currencyNameNatively: "Dollar néo-zélandais",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "mi"],
    digits: "0123456789",
    gdp: 4.1,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇳🇿",
  ),
  Country(
    name: "Mauritania",
    nameNatively: "موريتانيا",
    isoCode: "MR",
    iso3Code: "MRT",
    phoneCode: "+222",
    currencyCode: "MRU",
    currencyName: "Omani Rial",
    currencyNameNatively: "ريال عماني",
    currencySymbol: "UM",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["mr"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇷",
  ),
  Country(
    name: "Costa Rica",
    nameNatively: "Costa Rica",
    isoCode: "CR",
    iso3Code: "CRI",
    phoneCode: "+506",
    currencyCode: "CRC",
    currencyName: "Costa Rican Colón",
    currencyNameNatively: "Colón costarricense",
    currencySymbol: "₡",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 3.3,
    population: 0.1,
    wealthiest: 0.3,
    flag: "🇨🇷",
  ),
  Country(
    name: "Kuwait",
    nameNatively: "الكويت",
    isoCode: "KW",
    iso3Code: "KWT",
    phoneCode: "+965",
    currencyCode: "KWD",
    currencyName: "Kuwaiti Dinar",
    currencyNameNatively: "دينار كويتي",
    currencySymbol: "د.ك",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇰🇼",
  ),
  Country(
    name: "Panama",
    nameNatively: "Panamá",
    isoCode: "PA",
    iso3Code: "PAN",
    phoneCode: "+507",
    currencyCode: "PAB",
    currencyName: "Panamanian Balboa",
    currencyNameNatively: "Balboa",
    currencySymbol: "B/.",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "ngäbere"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇵🇦",
  ),
  Country(
    name: "Croatia",
    nameNatively: "Hrvatska",
    isoCode: "HR",
    iso3Code: "HRV",
    phoneCode: "+385",
    currencyCode: "HRK",
    currencyName: "Croatian Kuna",
    currencyNameNatively: "Kuna",
    currencySymbol: "kn",
    languageCode: "hr",
    languageName: "Croatian",
    languageNameNatively: "Hrvatski",
    languages: ["hr"],
    digits: "0123456789",
    gdp: 2.8,
    population: 0.1,
    wealthiest: 0.4,
    flag: "🇭🇷",
  ),
  Country(
    name: "Georgia",
    nameNatively: "საქართველო",
    isoCode: "GE",
    iso3Code: "GEO",
    phoneCode: "+995",
    currencyCode: "GEL",
    currencyName: "Georgian Lari",
    currencyNameNatively: "lari",
    currencySymbol: "₾",
    languageCode: "ka",
    languageName: "Georgian",
    languageNameNatively: "ქართული",
    languages: ["ka", "ru"],
    digits: "0123456789",
    gdp: 3.8,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇬🇪",
  ),
  Country(
    name: "Eritrea",
    nameNatively: "ኤርትራ",
    isoCode: "ER",
    iso3Code: "ERI",
    phoneCode: "+291",
    currencyCode: "ERN",
    currencyName: "Eritrean Nakfa",
    currencyNameNatively: "Nakfa",
    currencySymbol: "Nfk",
    languageCode: "ti",
    languageName: "Tigrinya",
    languageNameNatively: "Tigrinya",
    languages: ["ti", "arabic", "en"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇪🇷",
  ),
  Country(
    name: "Mongolia",
    nameNatively: "Монгол Улс",
    isoCode: "MN",
    iso3Code: "MNG",
    phoneCode: "+976",
    currencyCode: "MNT",
    currencyName: "Mongolian Tugrik",
    currencyNameNatively: "Tugrik",
    currencySymbol: "₮",
    languageCode: "mn",
    languageName: "Mongolian",
    languageNameNatively: "Монгол",
    languages: ["mn"],
    digits: "0123456789",
    gdp: 5.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇳",
  ),
  Country(
    name: "Uruguay",
    nameNatively: "Uruguay",
    isoCode: "UY",
    iso3Code: "URY",
    phoneCode: "+598",
    currencyCode: "UYU",
    currencyName: "Uruguayan Peso",
    currencyNameNatively: "Peso uruguayo",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇺🇾",
  ),
  Country(
    name: "Bosnia and Herzegovina",
    nameNatively: "Bosna i Hercegovina",
    isoCode: "BA",
    iso3Code: "BIH",
    phoneCode: "+387",
    currencyCode: "BAM",
    currencyName: "Bosnia and Herzegovina Convertible Mark",
    currencyNameNatively: "Konvertibilna marka",
    currencySymbol: "KM",
    languageCode: "bs",
    languageName: "Bosnian",
    languageNameNatively: "Bosanski",
    languages: ["bs", "hr", "sr"],
    digits: "0123456789",
    gdp: 2.8,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇦",
  ),
  Country(
    name: "Qatar",
    nameNatively: "قطر",
    isoCode: "QA",
    iso3Code: "QAT",
    phoneCode: "+974",
    currencyCode: "QAR",
    currencyName: "Qatari Rial",
    currencyNameNatively: "ريال قطري",
    currencySymbol: "﷼",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.1,
    wealthiest: 0.3,
    flag: "🇶🇦",
  ),
  Country(
    name: "Moldova",
    nameNatively: "Moldova",
    isoCode: "MD",
    iso3Code: "MDA",
    phoneCode: "+373",
    currencyCode: "MDL",
    currencyName: "Moldovan Leu",
    currencyNameNatively: "Leu moldovenesc",
    currencySymbol: "L",
    languageCode: "ro",
    languageName: "Romanian",
    languageNameNatively: "Română",
    languages: ["ro", "ru"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇩",
  ),
  Country(
    name: "Namibia",
    nameNatively: "Namibia",
    isoCode: "NA",
    iso3Code: "NAM",
    phoneCode: "+264",
    currencyCode: "NAD",
    currencyName: "Namibian Dollar",
    currencyNameNatively: "Dollar namibio",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇳🇦",
  ),
  Country(
    name: "Armenia",
    nameNatively: "Հայաստան",
    isoCode: "AM",
    iso3Code: "ARM",
    phoneCode: "+374",
    currencyCode: "AMD",
    currencyName: "Armenian Dram",
    currencyNameNatively: "դրամ",
    currencySymbol: "֏",
    languageCode: "hy",
    languageName: "Armenian",
    languageNameNatively: "Հայերեն",
    languages: ["hy", "ru"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇦🇲",
  ),
  Country(
    name: "Lithuania",
    nameNatively: "Lietuva",
    isoCode: "LT",
    iso3Code: "LTU",
    phoneCode: "+370",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euras",
    currencySymbol: "€",
    languageCode: "lt",
    languageName: "Lithuanian",
    languageNameNatively: "Lietuvių",
    languages: ["lt"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇹",
  ),
  Country(
    name: "Jamaica",
    nameNatively: "Jamaica",
    isoCode: "JM",
    iso3Code: "JAM",
    phoneCode: "+1",
    currencyCode: "JMD",
    currencyName: "Jamaican Dollar",
    currencyNameNatively: "Dollar jamaïcain",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇯🇲",
  ),
  Country(
    name: "Albania",
    nameNatively: "Shqipëria",
    isoCode: "AL",
    iso3Code: "ALB",
    phoneCode: "+355",
    currencyCode: "ALL",
    currencyName: "Albanian Lek",
    currencyNameNatively: "Leku",
    currencySymbol: "Lek",
    languageCode: "sq",
    languageName: "Albanian",
    languageNameNatively: "Shqip",
    languages: ["sq"],
    digits: "0123456789",
    gdp: 4.3,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇦🇱",
  ),
  Country(
    name: "Gambia",
    nameNatively: "The Gambia",
    isoCode: "GM",
    iso3Code: "GMB",
    phoneCode: "+220",
    currencyCode: "GMD",
    currencyName: "Gambian Dalasi",
    currencyNameNatively: "Dalasi",
    currencySymbol: "D",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇲",
  ),
  Country(
    name: "Gabon",
    nameNatively: "Gabon",
    isoCode: "GA",
    iso3Code: "GAB",
    phoneCode: "+241",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "₣",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇦",
  ),
  Country(
    name: "Botswana",
    nameNatively: "Botswana",
    isoCode: "BW",
    iso3Code: "BWA",
    phoneCode: "+267",
    currencyCode: "BWP",
    currencyName: "Botswana Pula",
    currencyNameNatively: "Pula",
    currencySymbol: "P",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.1,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇼",
  ),
  Country(
    name: "Lesotho",
    nameNatively: "Lesotho",
    isoCode: "LS",
    iso3Code: "LSO",
    phoneCode: "+266",
    currencyCode: "LSL",
    currencyName: "Lesotho Loti",
    currencyNameNatively: "Loti",
    currencySymbol: "M",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇸",
  ),
  Country(
    name: "Guinea-Bissau",
    nameNatively: "Guiné-Bissau",
    isoCode: "GW",
    iso3Code: "GNB",
    phoneCode: "+245",
    currencyCode: "XOF",
    currencyName: "Guinean Franc",
    currencyNameNatively: "Franco guineano",
    currencySymbol: "₣",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇼",
  ),
  Country(
    name: "Slovenia",
    nameNatively: "Slovenija",
    isoCode: "SI",
    iso3Code: "SVN",
    phoneCode: "+386",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "sl",
    languageName: "Slovene",
    languageNameNatively: "Slovenščina",
    languages: ["sl"],
    digits: "0123456789",
    gdp: 3.6,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇮",
  ),
  Country(
    name: "Equatorial Guinea",
    nameNatively: "Guinea Ecuatorial",
    isoCode: "GQ",
    iso3Code: "GNQ",
    phoneCode: "+240",
    currencyCode: "XAF",
    currencyName: "Central African CFA Franc",
    currencyNameNatively: "Franc CFA",
    currencySymbol: "FCFA",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["es", "fr"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇶",
  ),
  Country(
    name: "Latvia",
    nameNatively: "Latvija",
    isoCode: "LV",
    iso3Code: "LVA",
    phoneCode: "+371",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "lv",
    languageName: "Latvian",
    languageNameNatively: "Latviešu",
    languages: ["lv"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇻",
  ),
  Country(
    name: "North Macedonia",
    nameNatively: "Северна Македонија",
    isoCode: "MK",
    iso3Code: "MKD",
    phoneCode: "+389",
    currencyCode: "MKD",
    currencyName: "Macedonian Denar",
    currencyNameNatively: "Денар",
    currencySymbol: "ден",
    languageCode: "mk",
    languageName: "Macedonian",
    languageNameNatively: "Македонски",
    languages: ["mk"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇰",
  ),
  Country(
    name: "Bahrain",
    nameNatively: "البحرين",
    isoCode: "BH",
    iso3Code: "BHR",
    phoneCode: "+973",
    currencyCode: "BHD",
    currencyName: "Bahraini Dinar",
    currencyNameNatively: "دينار بحريني",
    currencySymbol: ".د.ب",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "en"],
    digits: "0123456789",
    gdp: 2.3,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇧🇭",
  ),
  Country(
    name: "Trinidad and Tobago",
    nameNatively: "Trinidad and Tobago",
    isoCode: "TT",
    iso3Code: "TTO",
    phoneCode: "+1",
    currencyCode: "TTD",
    currencyName: "Trinidad and Tobago Dollar",
    currencyNameNatively: "Dollar de Trinité-et-Tobago",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "hi"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.2,
    flag: "🇹🇹",
  ),
  Country(
    name: "Timor-Leste",
    nameNatively: "Timor-Leste",
    isoCode: "TL",
    iso3Code: "TLS",
    phoneCode: "+670",
    currencyCode: "USD",
    currencyName: "East Timorese Metical",
    currencyNameNatively: "Metical",
    currencySymbol: "₨",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["tet"],
    digits: "0123456789",
    gdp: 4.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇱",
  ),
  Country(
    name: "Estonia",
    nameNatively: "Eesti",
    isoCode: "EE",
    iso3Code: "EST",
    phoneCode: "+372",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "et",
    languageName: "Estonian",
    languageNameNatively: "Eesti",
    languages: ["et"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇪🇪",
  ),
  Country(
    name: "Cyprus",
    nameNatively: "Κύπρος",
    isoCode: "CY",
    iso3Code: "CYP",
    phoneCode: "+357",
    currencyCode: "EUR",
    currencyName: "Cypriot Pound",
    currencyNameNatively: "Pound chypriote",
    currencySymbol: "€",
    languageCode: "el",
    languageName: "Greek",
    languageNameNatively: "Ελληνικά",
    languages: ["el", "tr"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇨🇾",
  ),
  Country(
    name: "Mauritius",
    nameNatively: "Maurice",
    isoCode: "MU",
    iso3Code: "MUS",
    phoneCode: "+230",
    currencyCode: "MUR",
    currencyName: "Mauritian Rupee",
    currencyNameNatively: "Roupie mauricienne",
    currencySymbol: "₨",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "fr"],
    digits: "0123456789",
    gdp: 3.4,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇺",
  ),
  Country(
    name: "Eswatini",
    nameNatively: "eSwatini",
    isoCode: "SZ",
    iso3Code: "SWZ",
    phoneCode: "+268",
    currencyCode: "SZL",
    currencyName: "Swazi Lilangeni",
    currencyNameNatively: "Lilangeni",
    currencySymbol: "Lilangeni",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇿",
  ),
  Country(
    name: "Djibouti",
    nameNatively: "Djibouti",
    isoCode: "DJ",
    iso3Code: "DJI",
    phoneCode: "+253",
    currencyCode: "DJF",
    currencyName: "Djiboutian Franc",
    currencyNameNatively: "Franc djiboutien",
    currencySymbol: "Fdj",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "fr"],
    digits: "0123456789",
    gdp: 3.3,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇩🇯",
  ),
  Country(
    name: "Fiji",
    nameNatively: "Fiji",
    isoCode: "FJ",
    iso3Code: "FJI",
    phoneCode: "+679",
    currencyCode: "FJD",
    currencyName: "Fijian Dollar",
    currencyNameNatively: "Dollar fidjien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇫🇯",
  ),
  Country(
    name: "Comoros",
    nameNatively: "Comores",
    isoCode: "KM",
    iso3Code: "COM",
    phoneCode: "+269",
    currencyCode: "KMF",
    currencyName: "Comorian Franc",
    currencyNameNatively: "Franc comorien",
    currencySymbol: "KMF",
    languageCode: "ar",
    languageName: "Arabic",
    languageNameNatively: "العربية",
    languages: ["ar", "fr", "comorian"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇰🇲",
  ),
  Country(
    name: "Guyana",
    nameNatively: "Guyana",
    isoCode: "GY",
    iso3Code: "GUY",
    phoneCode: "+592",
    currencyCode: "GYD",
    currencyName: "Guyanese Dollar",
    currencyNameNatively: "Dollar guyanien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇾",
  ),
  Country(
    name: "Solomon Islands",
    nameNatively: "Solomon Islands",
    isoCode: "SB",
    iso3Code: "SLB",
    phoneCode: "+677",
    currencyCode: "SBD",
    currencyName: "Solomon Islands Dollar",
    currencyNameNatively: "Dollar des îles Salomon",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "melanesian", "pijin"],
    digits: "0123456789",
    gdp: 3.8,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇧",
  ),
  Country(
    name: "Bhutan",
    nameNatively: "འབྲུག",
    isoCode: "BT",
    iso3Code: "BTN",
    phoneCode: "+975",
    currencyCode: "BTN",
    currencyName: "Bhutanese Ngultrum",
    currencyNameNatively: "Ngultrum",
    currencySymbol: "Nu",
    languageCode: "dz",
    languageName: "Dzongkha",
    languageNameNatively: "རྫོང་ཁ",
    languages: ["dz"],
    digits: "0123456789",
    gdp: 5.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇹",
  ),
  Country(
    name: "Luxembourg",
    nameNatively: "Lëtzebuerg",
    isoCode: "LU",
    iso3Code: "LUX",
    phoneCode: "+352",
    currencyCode: "EUR",
    currencyName: "Luxembourg Franc",
    currencyNameNatively: "Franc luxembourgeois",
    currencySymbol: "€",
    languageCode: "lb",
    languageName: "Luxembourgish",
    languageNameNatively: "Lëtzebuergesch",
    languages: ["lb", "fr", "de"],
    digits: "0123456789",
    gdp: 3.1,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇺",
  ),
  Country(
    name: "Montenegro",
    nameNatively: "Crna Gora",
    isoCode: "ME",
    iso3Code: "MNE",
    phoneCode: "+382",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "sr",
    languageName: "Serbian",
    languageNameNatively: "Српски",
    languages: ["sr", "me"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇪",
  ),
  Country(
    name: "Suriname",
    nameNatively: "Suriname",
    isoCode: "SR",
    iso3Code: "SUR",
    phoneCode: "+597",
    currencyCode: "SRD",
    currencyName: "Surinamese Dollar",
    currencyNameNatively: "Dollar surinamien",
    currencySymbol: "SRD",
    languageCode: "sr",
    languageName: "Serbian",
    languageNameNatively: "Српски",
    languages: ["sr"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇷",
  ),
  Country(
    name: "Malta",
    nameNatively: "Malta",
    isoCode: "MT",
    iso3Code: "MLT",
    phoneCode: "+356",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "mt",
    languageName: "Maltese",
    languageNameNatively: "Maltese",
    languages: ["mt"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇹",
  ),
  Country(
    name: "Maldives",
    nameNatively: "Maldives",
    isoCode: "MV",
    iso3Code: "MDV",
    phoneCode: "+960",
    currencyCode: "MVR",
    currencyName: "Maldivian Rufiyaa",
    currencyNameNatively: "Rufiyaa",
    currencySymbol: "Rf",
    languageCode: "dv",
    languageName: "Dhivehi",
    languageNameNatively: "ދިވެހި",
    languages: ["dv"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇲🇻",
  ),
  Country(
    name: "Federated States of Micronesia",
    nameNatively: "Federated States of Micronesia",
    isoCode: "FM",
    iso3Code: "FSM",
    phoneCode: "+691",
    currencyCode: "USD",
    currencyName: "Micronesian Dollar",
    currencyNameNatively: "Dollar micronésien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "chk", "pon"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇫🇲",
  ),
  Country(
    name: "Cape Verde",
    nameNatively: "Cabo Verde",
    isoCode: "CV",
    iso3Code: "CPV",
    phoneCode: "+238",
    currencyCode: "CVE",
    currencyName: "Cape Verdean Escudo",
    currencyNameNatively: "Escudo caboverdiano",
    currencySymbol: "Esc",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 4.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇨🇻",
  ),
  Country(
    name: "Brunei",
    nameNatively: "Brunei",
    isoCode: "BN",
    iso3Code: "BRN",
    phoneCode: "+673",
    currencyCode: "BND",
    currencyName: "Brunei Dollar",
    currencyNameNatively: "Dollar de Brunei",
    currencySymbol: "\$",
    languageCode: "ms",
    languageName: "Malay",
    languageNameNatively: "বাংলা",
    languages: ["ms", "en"],
    digits: "0123456789",
    gdp: 5.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇳",
  ),
  Country(
    name: "Belize",
    nameNatively: "Belize",
    isoCode: "BZ",
    iso3Code: "BLZ",
    phoneCode: "+501",
    currencyCode: "BZD",
    currencyName: "Belize Dollar",
    currencyNameNatively: "Dollar bélizien",
    currencySymbol: "\$",
    languageCode: "es",
    languageName: "Spanish",
    languageNameNatively: "Español",
    languages: ["en"],
    digits: "0123456789",
    gdp: 4.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇿",
  ),
  Country(
    name: "Bahamas",
    nameNatively: "Bahamas",
    isoCode: "BS",
    iso3Code: "BHS",
    phoneCode: "+1",
    currencyCode: "BSD",
    currencyName: "Bahamian Dollar",
    currencyNameNatively: "Dollar bahaméen",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇸",
  ),
  Country(
    name: "Iceland",
    nameNatively: "Ísland",
    isoCode: "IS",
    iso3Code: "ISL",
    phoneCode: "+354",
    currencyCode: "ISK",
    currencyName: "Icelandic Króna",
    currencyNameNatively: "Króna",
    currencySymbol: "kr",
    languageCode: "is",
    languageName: "Icelandic",
    languageNameNatively: "Íslenska",
    languages: ["is"],
    digits: "0123456789",
    gdp: 2.4,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇮🇸",
  ),
  Country(
    name: "Vanuatu",
    nameNatively: "Vanuatu",
    isoCode: "VU",
    iso3Code: "VUT",
    phoneCode: "+678",
    currencyCode: "VUV",
    currencyName: "Vanuatu Vatu",
    currencyNameNatively: "Vatu",
    currencySymbol: "Vt",
    languageCode: "bi",
    languageName: "Bislama",
    languageNameNatively: "Bislama",
    languages: ["bi", "en"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇻🇺",
  ),
  Country(
    name: "Barbados",
    nameNatively: "Barbados",
    isoCode: "BB",
    iso3Code: "BRB",
    phoneCode: "+1",
    currencyCode: "BBD",
    currencyName: "Barbadian Dollar",
    currencyNameNatively: "Dollar barbadien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.6,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇧🇧",
  ),
  Country(
    name: "Sao Tome and Principe",
    nameNatively: "São Tomé e Príncipe",
    isoCode: "ST",
    iso3Code: "STP",
    phoneCode: "+239",
    currencyCode: "STN",
    currencyName: "São Tomé and Príncipe Dobra",
    currencyNameNatively: "Dobra",
    currencySymbol: "Dobra",
    languageCode: "pt",
    languageName: "Portuguese",
    languageNameNatively: "Português",
    languages: ["pt"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇹",
  ),
  Country(
    name: "Samoa",
    nameNatively: "Samoa",
    isoCode: "WS",
    iso3Code: "WSM",
    phoneCode: "+685",
    currencyCode: "WST",
    currencyName: "Samoan Tala",
    currencyNameNatively: "Tala",
    currencySymbol: "Tala",
    languageCode: "sm",
    languageName: "Samoan",
    languageNameNatively: "Samoan",
    languages: ["sm", "en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇼🇸",
  ),
  Country(
    name: "Saint Lucia",
    nameNatively: "Saint Lucia",
    isoCode: "LC",
    iso3Code: "LCA",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "EC\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇱🇨",
  ),
  Country(
    name: "Kiribati",
    nameNatively: "Kiribati",
    isoCode: "KI",
    iso3Code: "KIR",
    phoneCode: "+686",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    currencyNameNatively: "Dollar australien",
    currencySymbol: "A\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇰🇮",
  ),
  Country(
    name: "Seychelles",
    nameNatively: "Seychelles",
    isoCode: "SC",
    iso3Code: "SYC",
    phoneCode: "+248",
    currencyCode: "SCR",
    currencyName: "Seychelles Rupee",
    currencyNameNatively: "Roupie seychelloise",
    currencySymbol: "₨",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇸🇨",
  ),
  Country(
    name: "Grenada",
    nameNatively: "Grenada",
    isoCode: "GD",
    iso3Code: "GRD",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇬🇩",
  ),
  Country(
    name: "Tonga",
    nameNatively: "Tonga",
    isoCode: "TO",
    iso3Code: "TON",
    phoneCode: "+676",
    currencyCode: "TOP",
    currencyName: "Tongan Paʻanga",
    currencyNameNatively: "Paʻanga",
    currencySymbol: "Paʻanga",
    languageCode: "to",
    languageName: "Tongan",
    languageNameNatively: "Faka-Tonga",
    languages: ["to"],
    digits: "0123456789",
    gdp: 3.1,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇹🇴",
  ),
  Country(
    name: "Saint Vincent and the Grenadines",
    nameNatively: "Saint Vincent and the Grenadines",
    isoCode: "VC",
    iso3Code: "VCT",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇻🇨",
  ),
  Country(
    name: "Antigua and Barbuda",
    nameNatively: "Antigua and Barbuda",
    isoCode: "AG",
    iso3Code: "ATG",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "EC\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.5,
    population: 0.1,
    wealthiest: 0.1,
    flag: "🇦🇬",
  ),
  Country(
    name: "Andorra",
    nameNatively: "Andorra",
    isoCode: "AD",
    iso3Code: "AND",
    phoneCode: "+376",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "ca",
    languageName: "Catalan",
    languageNameNatively: "Català",
    languages: ["ca"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇦🇩",
  ),
  Country(
    name: "Dominica",
    nameNatively: "Dominica",
    isoCode: "DM",
    iso3Code: "DMA",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.2,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇩🇲",
  ),
  Country(
    name: "Saint Kitts and Nevis",
    nameNatively: "Saint Kitts and Nevis",
    isoCode: "KN",
    iso3Code: "KNA",
    phoneCode: "+1",
    currencyCode: "XCD",
    currencyName: "East Caribbean Dollar",
    currencyNameNatively: "Dollar des Caraïbes orientales",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇰🇳",
  ),
  Country(
    name: "Liechtenstein",
    nameNatively: "Liechtenstein",
    isoCode: "LI",
    iso3Code: "LIE",
    phoneCode: "+423",
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    currencyNameNatively: "Franc suisse",
    currencySymbol: "Fr",
    languageCode: "de",
    languageName: "German",
    languageNameNatively: "Deutsch",
    languages: ["de"],
    digits: "0123456789",
    gdp: 2.8,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇱🇮",
  ),
  Country(
    name: "Monaco",
    nameNatively: "Monaco",
    isoCode: "MC",
    iso3Code: "MCO",
    phoneCode: "+377",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "fr",
    languageName: "French",
    languageNameNatively: "Français",
    languages: ["fr"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇲🇨",
  ),
  Country(
    name: "Marshall Islands",
    nameNatively: "Marshall Islands",
    isoCode: "MH",
    iso3Code: "MHL",
    phoneCode: "+692",
    currencyCode: "USD",
    currencyName: "United States Dollar",
    currencyNameNatively: "Dollar des États-Unis",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en", "mh"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇲🇭",
  ),
  Country(
    name: "San Marino",
    nameNatively: "San Marino",
    isoCode: "SM",
    iso3Code: "SMR",
    phoneCode: "+378",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "it",
    languageName: "Italian",
    languageNameNatively: "Italiano",
    languages: ["it"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇸🇲",
  ),
  Country(
    name: "Palau",
    nameNatively: "Palau",
    isoCode: "PW",
    iso3Code: "PLW",
    phoneCode: "+680",
    currencyCode: "USD",
    currencyName: "United States Dollar",
    currencyNameNatively: "Dollar des États-Unis",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 2.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇵🇼",
  ),
  Country(
    name: "Nauru",
    nameNatively: "Nauru",
    isoCode: "NR",
    iso3Code: "NRU",
    phoneCode: "+674",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    currencyNameNatively: "Dollar australien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 3.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇳🇷",
  ),
  Country(
    name: "Tuvalu",
    nameNatively: "Tuvalu",
    isoCode: "TV",
    iso3Code: "TUV",
    phoneCode: "+688",
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    currencyNameNatively: "Dollar australien",
    currencySymbol: "\$",
    languageCode: "en",
    languageName: "English",
    languageNameNatively: "English",
    languages: ["en"],
    digits: "0123456789",
    gdp: 1.5,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇹🇻",
  ),
  Country(
    name: "Vatican City",
    nameNatively: "Vatican City",
    isoCode: "VA",
    iso3Code: "VAT",
    phoneCode: "+39",
    currencyCode: "EUR",
    currencyName: "Euro",
    currencyNameNatively: "Euro",
    currencySymbol: "€",
    languageCode: "it",
    languageName: "Italian",
    languageNameNatively: "Italiano",
    languages: ["la"],
    digits: "0123456789",
    gdp: 0.0,
    population: 0.0,
    wealthiest: 0.0,
    flag: "🇻🇦",
  )
];
