const kCountryCurrencyNamesInEnglish = {
  "IN": "Indian Rupee",
  "CN": "Yuan Renminbi",
  "US": "United States Dollar",
  "ID": "Indonesian Rupiah",
  "PK": "Pakistani Rupee",
  "NG": "Nigerian Naira",
  "BR": "Brazilian Real",
  "BD": "Bangladeshi Taka",
  "RU": "Russian Ruble",
  "ET": "Ethiopian Birr",
  "MX": "Mexican Peso",
  "JP": "Japanese Yen",
  "EG": "Egyptian Pound",
  "PH": "Philippine Peso",
  "CD": "Congolese Franc",
  "VN": "Vietnamese Dong",
  "IR": "Iranian Rial",
  "TR": "Turkish Lira",
  "DE": "Euro",
  "TH": "Thai Baht",
  "GB": "Pound Sterling",
  "TZ": "Tanzanian Shilling",
  "FR": "Euro",
  "ZA": "South African Rand",
  "IT": "Euro",
  "KE": "Kenyan Shilling",
  "MM": "Burmese Kyat",
  "CO": "Colombian Peso",
  "KR": "South Korean Won",
  "SD": "Sudanese Pound",
  "UG": "Ugandan Shilling",
  "ES": "Euro",
  "DZ": "Algerian Dinar",
  "IQ": "Iraqi Dinar",
  "AR": "Argentine Peso",
  "AF": "Afghan Afghani",
  "YE": "Yemeni Rial",
  "CA": "Canadian Dollar",
  "PL": "Polish Zloty",
  "MA": "Moroccan Dirham",
  "AO": "Angolan Kwanza",
  "UA": "Ukrainian Hryvnia",
  "UZ": "Uzbekistani Som",
  "MY": "Malaysian Ringgit",
  "MZ": "Mozambican Metical",
  "GH": "Ghanaian Cedi",
  "PE": "Peruvian Nuevo Sol",
  "SA": "Saudi Riyal",
  "MG": "Malagasy Ariary",
  "CI": "West African CFA Franc",
  "NP": "Nepalese Rupee",
  "CM": "Central African CFA Franc",
  "VE": "Venezuelan Bolívar",
  "NE": "West African CFA Franc",
  "AU": "Australian Dollar",
  "KP": "North Korean Won",
  "SY": "Syrian Pound",
  "ML": "West African CFA Franc",
  "BF": "West African CFA Franc",
  "LK": "Sri Lankan Rupee",
  "MW": "Malawian Kwacha",
  "ZM": "Zambian Kwacha",
  "KZ": "Kazakhstani Tenge",
  "TD": "Central African CFA Franc",
  "CL": "Chilean Peso",
  "RO": "Romanian Leu",
  "SO": "Somali Shilling",
  "SN": "West African CFA Franc",
  "GT": "Guatemalan Quetzal",
  "NL": "Euro",
  "EC": "United States Dollar",
  "KH": "Cambodian Riel",
  "ZW": "Zimbabwean Dollar",
  "GN": "Guinean Franc",
  "BJ": "West African CFA Franc",
  "RW": "Rwandan Franc",
  "BI": "Burundian Franc",
  "BO": "Bolivian Boliviano",
  "TN": "Tunisian Dinar",
  "SS": "South Sudanese Pound",
  "HT": "Haitian Gourde",
  "BE": "Euro",
  "JO": "Jordanian Dinar",
  "DO": "Dominican Peso",
  "AE": "United Arab Emirates Dirham",
  "CU": "Cuban Peso",
  "HN": "Honduran Lempira",
  "CZ": "Czech Koruna",
  "SE": "Swedish Krona",
  "TJ": "Tajikistani Somoni",
  "PG": "Papua New Guinean Kina",
  "PT": "Euro",
  "AZ": "Azerbaijani Manat",
  "GR": "Euro",
  "HU": "Hungarian Forint",
  "TG": "West African CFA Franc",
  "IL": "Israeli New Shekel",
  "AT": "Euro",
  "BY": "Belarusian Ruble",
  "CH": "Swiss Franc",
  "SL": "Sierra Leonean Leone",
  "LA": "Lao Kip",
  "TM": "Turkmenistan Manat",
  "LY": "Libyan Dinar",
  "KG": "Kyrgyzstani Som",
  "PY": "Paraguayan Guarani",
  "NI": "Nicaraguan Córdoba",
  "BG": "Bulgarian Lev",
  "RS": "Serbian Dinar",
  "SV": "El Salvadoran Colón",
  "CG": "Central African CFA Franc",
  "DK": "Danish Krone",
  "SG": "Singapore Dollar",
  "LB": "Lebanese Pound",
  "FI": "Euro",
  "LR": "Liberian Dollar",
  "NO": "Norwegian Krone",
  "SK": "Slovak Koruna",
  "PS": "Israeli New Shekel",
  "CF": "Central African CFA Franc",
  "OM": "Omani Rial",
  "IE": "Euro",
  "NZ": "New Zealand Dollar",
  "MR": "Omani Rial",
  "CR": "Costa Rican Colón",
  "KW": "Kuwaiti Dinar",
  "PA": "Panamanian Balboa",
  "HR": "Croatian Kuna",
  "GE": "Georgian Lari",
  "ER": "Eritrean Nakfa",
  "MN": "Mongolian Tugrik",
  "UY": "Uruguayan Peso",
  "BA": "Bosnia and Herzegovina Convertible Mark",
  "QA": "Qatari Rial",
  "MD": "Moldovan Leu",
  "NA": "Namibian Dollar",
  "AM": "Armenian Dram",
  "LT": "Euro",
  "JM": "Jamaican Dollar",
  "AL": "Albanian Lek",
  "GM": "Gambian Dalasi",
  "GA": "Central African CFA Franc",
  "BW": "Botswana Pula",
  "LS": "Lesotho Loti",
  "GW": "Guinean Franc",
  "SI": "Euro",
  "GQ": "Central African CFA Franc",
  "LV": "Euro",
  "MK": "Macedonian Denar",
  "BH": "Bahraini Dinar",
  "TT": "Trinidad and Tobago Dollar",
  "TL": "East Timorese Metical",
  "EE": "Euro",
  "CY": "Cypriot Pound",
  "MU": "Mauritian Rupee",
  "SZ": "Swazi Lilangeni",
  "DJ": "Djiboutian Franc",
  "FJ": "Fijian Dollar",
  "KM": "Comorian Franc",
  "GY": "Guyanese Dollar",
  "SB": "Solomon Islands Dollar",
  "BT": "Bhutanese Ngultrum",
  "LU": "Luxembourg Franc",
  "ME": "Euro",
  "SR": "Surinamese Dollar",
  "MT": "Euro",
  "MV": "Maldivian Rufiyaa",
  "FM": "Micronesian Dollar",
  "CV": "Cape Verdean Escudo",
  "BN": "Brunei Dollar",
  "BZ": "Belize Dollar",
  "BS": "Bahamian Dollar",
  "IS": "Icelandic Króna",
  "VU": "Vanuatu Vatu",
  "BB": "Barbadian Dollar",
  "ST": "São Tomé and Príncipe Dobra",
  "WS": "Samoan Tala",
  "LC": "East Caribbean Dollar",
  "KI": "Australian Dollar",
  "SC": "Seychelles Rupee",
  "GD": "East Caribbean Dollar",
  "TO": "Tongan Paʻanga",
  "VC": "East Caribbean Dollar",
  "AG": "East Caribbean Dollar",
  "AD": "Euro",
  "DM": "East Caribbean Dollar",
  "KN": "East Caribbean Dollar",
  "LI": "Swiss Franc",
  "MC": "Euro",
  "MH": "United States Dollar",
  "SM": "Euro",
  "PW": "United States Dollar",
  "NR": "Australian Dollar",
  "TV": "Australian Dollar",
  "VA": "Euro",
  "TW": "New Taiwan Dollar"
};
