const kLanguageNamesInNative = {
  "af": "Afrikaans",
  "sq": "Shqip",
  "am": "አማርኛ",
  "ar": "العربية",
  "hy": "Հայերեն",
  "az": "Azərbaycanca",
  "eu": "Euskara",
  "be": "Беларуская",
  "bn": "বাংলা",
  "bs": "Bosanski",
  "bg": "Български",
  "ca": "Català",
  "ceb": "Cebuano",
  "ny": "Chichewa",
  "zh_CN": "中文",
  "zh_TW": "繁體中文",
  "co": "Corsu",
  "hr": "Hrvatski",
  "cs": "Čeština",
  "da": "Dansk",
  "nl": "Nederlands",
  "en": "English",
  "eo": "Esperanto",
  "et": "Eesti",
  "tl": "Filipino",
  "fi": "Suomi",
  "fr": "Français",
  "fy": "Frysk",
  "gl": "Galego",
  "ka": "ქართული",
  "de": "Deutsch",
  "el": "Ελληνικά",
  "gu": "ગુજરાતી",
  "ht": "Kreyòl Ayisyen",
  "ha": "Hausa",
  "haw": "ʻŌlelo Hawaiʻi",
  "he": "עברית",
  "hi": "हिन्दी",
  "hmn": "Hmong",
  "hu": "Magyar",
  "is": "Íslenska",
  "ig": "Igbo",
  "id": "Bahasa Indonesia",
  "ga": "Gaeilge",
  "it": "Italiano",
  "ja": "日本語",
  "jw": "Basa Jawa",
  "kn": "ಕನ್ನಡ",
  "kk": "Қазақ тілі",
  "km": "ខ្មែរ",
  "ko": "한국어",
  "ku": "Kurdî",
  "ky": "Кыргызча",
  "lo": "ລາວ",
  "la": "Latina",
  "lv": "Latviešu",
  "lt": "Lietuvių",
  "lb": "Lëtzebuergesch",
  "mk": "Македонски",
  "mg": "Malagasy",
  "ms": "Bahasa Melayu",
  "ml": "മലയാളം",
  "mt": "Malti",
  "mi": "Māori",
  "mr": "मराठी",
  "mn": "Монгол",
  "my": "မြန်မာစာ",
  "ne": "नेपाली",
  "no": "Norsk",
  "or": "ଓଡ଼ିଆ",
  "ps": "پښتو",
  "fa": "فارسی",
  "pl": "Polski",
  "pt": "Português",
  "pa": "ਪੰਜਾਬੀ",
  "ro": "Română",
  "ru": "Русский",
  "sm": "Gagana Samoa",
  "gd": "Gàidhlig",
  "sr": "Српски",
  "st": "Sesotho",
  "sn": "Shona",
  "sd": "سنڌي",
  "si": "සිංහල",
  "sk": "Slovenčina",
  "sl": "Slovenščina",
  "so": "Soomaali",
  "es": "Español",
  "su": "Basa Sunda",
  "sw": "Kiswahili",
  "sv": "Svenska",
  "tg": "Тоҷикӣ",
  "ta": "தமிழ்",
  "te": "తెలుగు",
  "th": "ไทย",
  "tr": "Türkçe",
  "uk": "Українська",
  "ur": "اردو",
  "ug": "ئۇيغۇرچە",
  "uz": "Oʻzbekcha",
  "vi": "Tiếng Việt",
  "cy": "Cymraeg",
  "xh": "isiXhosa",
  "yi": "ייִדיש",
  "yo": "Yorùbá",
  "zu": "isiZulu"
};
