/// A utility class for generating keys.
part of '../utils.dart';

class KeyProvider {
  const KeyProvider._();

  /// Generates a unique image key based on the current date and time.
  ///
  /// Example:
  /// ```dart
  /// String imageKey = KeyProvider.imgKey;
  /// print(imageKey); // Output: Current date and time formatted as 'yyyyMMddHHmmss'.
  /// ```
  static String get imgKey {
    final a = DateTime.now();
    return "${a.year.x4D}${a.month.x2D}${a.day.x2D}${a.hour.x2D}${a.minute.x2D}${a.second.x2D}";
  }

  /// Generates a key based on the provided name or the current timestamp.
  ///
  /// Parameters:
  /// - [name]: The name to generate a key from. If provided, the key is generated by converting the name to lowercase.
  /// - [timeMills]: The timestamp to generate a key from. If not provided, the current timestamp is used.
  /// - [extraKeySize]: The size of the extra key to append. Default is 5.
  ///
  /// Example:
  /// ```dart
  /// String key = KeyProvider.generateKey(name: 'MyImage');
  /// print(key); // Output: 'myimage'
  ///
  /// String timestampKey = KeyProvider.generateKey(timeMills: 1644613725000);
  /// print(timestampKey); // Output: '1644613725000xxxxx' (xxxxx is a random string of 5 characters)
  /// ```
  static String generateKey({
    String? name,
    int? timeMills,
    int extraKeySize = 5,
  }) {
    if (name != null) {
      return Replacement.auto(name).toLowerCase();
    } else {
      final ms = timeMills ?? DateProvider.currentMS;
      final extra = RandomProvider.getString(
        data: KeyFormat.allowedNumbers,
        max: extraKeySize,
      );
      final key = "$ms$extra";
      return key;
    }
  }
}
